# 00 - Data Preprocessing & Dataset Pipeline

This notebook prepares the dataset for the ProphetLSTM-GAN project.

We are working with a multivariate time-series anomaly detection problem. The raw data
consists of multiple sensor channels logged over time for **normal** and **faulty/anomalous**
operating conditions. Our goal in this notebook is to turn those raw CSV logs into clean,
normalized and windowed tensors that can be directly fed into our LSTM-GAN / VAE-GAN
models.

---

## Objectives

1. **Load raw data**
   - Read all CSV files from `data/raw/train/` and `data/raw/test/`.
   - Concatenate them into continuous time-series for each split.

2. **Basic sanity checks**
   - Inspect shapes, dtypes, missing values.
   - Verify time index continuity (or at least monotonicity).

3. **Preprocessing pipeline**
   - Select relevant columns (sensor channels, time index).
   - Handle NaNs / constant columns if any.
   - Apply scaling / normalization (e.g. MinMaxScaler or StandardScaler).

4. **Windowing**
   - Convert long sequences into overlapping sliding windows:
     - shape: `(num_windows, window_length, num_features)`
   - Create consistent **train / val / test** splits.

5. **Save processed artifacts**
   - Save `X_train`, `X_val`, `X_test` (and optionally labels `y_*` if available)
     under `data/processed/` as `.npz` or `.npy` files.
   - These will be loaded in `01_training.ipynb` and `02_evaluation.ipynb`.

---

## Notebook layout

1. Imports & configuration  
2. Load raw CSVs (train/test)  
3. Exploratory checks (head, info, missing values)  
4. Column selection & cleaning  
5. Scaling / normalization  
6. Sliding-window generator  
7. Train/val/test split  
8. Save processed arrays to `data/processed/`

> **Note:** This notebook does **not** train any models. It only builds a clean, reusable
> data pipeline so that all later notebooks can rely on the same preprocessing.

### **Testing the GPU.**

In [2]:
import torch
print("Device:", torch.cuda.get_device_name(0))

Device: NVIDIA GeForce RTX 4060 Laptop GPU

In [3]:
import warnings
warnings.filterwarnings("ignore", category=UserWarning)

## 1. Imports and path setup

In this section we:
- Import the core Python libraries
- Define paths relative to the project root
- Make sure the `data/raw/train` and `data/raw/test` folders are visible

In [4]:
import os
import glob

import numpy as np
import pandas as pd

from pathlib import Path

# Set project root as the parent of this notebook
PROJECT_ROOT = Path.cwd()

DATA_DIR = PROJECT_ROOT / "data"
RAW_DIR = DATA_DIR / "raw"
TRAIN_RAW_DIR = RAW_DIR / "train"
TEST_RAW_DIR = RAW_DIR / "test"
PROCESSED_DIR = DATA_DIR / "processed"

# Create processed dir if it doesn't exist
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

print("Project root :", PROJECT_ROOT)
print("Raw train dir:", TRAIN_RAW_DIR)
print("Raw test dir :", TEST_RAW_DIR)
print("Processed dir:", PROCESSED_DIR)

print("\nTrain CSVs found:")
for f in sorted(TRAIN_RAW_DIR.glob("*.csv")):
    print(" -", f.name)

print("\nTest CSVs found:")
for f in sorted(TEST_RAW_DIR.glob("*.csv")):
    print(" -", f.name)

Project root : C:\Users\aymisxx\Documents\GitHub\ProphetLSTM-GAN
Raw train dir: C:\Users\aymisxx\Documents\GitHub\ProphetLSTM-GAN\data\raw\train
Raw test dir : C:\Users\aymisxx\Documents\GitHub\ProphetLSTM-GAN\data\raw\test
Processed dir: C:\Users\aymisxx\Documents\GitHub\ProphetLSTM-GAN\data\processed

Train CSVs found:
 - 00001_001_SN01_24bars_ssf.csv
 - 00002_002_SN01_21bars_ssf.csv
 - 00003_003_SN01_18bars_ssf.csv
 - 00004_004_SN01_15bars_ssf.csv
 - 00005_005_SN01_12bars_ssf.csv
 - 00006_006_SN01_9bars_ssf.csv
 - 00007_007_SN01_24bars_health_check.csv
 - 00008_008_SN01_21bars_health_check.csv
 - 00009_009_SN01_18bars_health_check.csv
 - 00010_010_SN01_15bars_health_check.csv
 - 00011_011_SN01_12bars_health_check.csv
 - 00012_012_SN01_9bars_health_check.csv
 - 00013_013_SN01_24bars_ramp1.csv
 - 00014_014_SN01_24bars_ramp2.csv
 - 00015_015_SN01_24bars_ramp3.csv
 - 00016_016_SN01_24bars_ramp4.csv
 - 00017_017_SN01_24bars_onmod.csv
 - 00018_018_SN01_24bars_offmod.csv
 - 00019_019_SN01_24bars_random_short.csv
 - 00020_020_SN01_24bars_random_long.csv
 - 00021_021_SN01_24bars_random_mixed.csv
 - 00022_022_SN01_21bars_ramp1.csv
 - 00023_023_SN01_21bars_ramp2.csv
 - 00024_024_SN01_21bars_ramp3.csv
 - 00025_025_SN01_21bars_ramp4.csv
 - 00026_026_SN01_21bars_onmod.csv
 - 00027_027_SN01_21bars_offmod.csv
 - 00028_028_SN01_21bars_random_short.csv
 - 00029_029_SN01_21bars_random_long.csv
 - 00030_030_SN01_21bars_random_mixed.csv
 - 00031_031_SN01_18bars_ramp1.csv
 - 00032_032_SN01_18bars_ramp2.csv
 - 00033_033_SN01_18bars_ramp3.csv
 - 00034_034_SN01_18bars_ramp4.csv
 - 00035_035_SN01_18bars_onmod.csv
 - 00036_036_SN01_18bars_offmod.csv
 - 00037_037_SN01_18bars_random_short.csv
 - 00038_038_SN01_18bars_random_long.csv
 - 00039_039_SN01_18bars_random_mixed.csv
 - 00040_040_SN01_24bars_ssf.csv
 - 00041_041_SN01_21bars_ssf.csv
 - 00042_042_SN01_18bars_ssf.csv
 - 00043_043_SN01_15bars_ssf.csv
 - 00044_044_SN01_12bars_ssf.csv
 - 00045_045_SN01_9bars_ssf.csv
 - 00046_046_SN01_24bars_health_check.csv
 - 00047_047_SN01_21bars_health_check.csv
 - 00048_048_SN01_18bars_health_check.csv
 - 00049_049_SN01_15bars_health_check.csv
 - 00050_050_SN01_12bars_health_check.csv
 - 00051_051_SN01_9bars_health_check.csv
 - 00052_052_SN01_15bars_ramp1.csv
 - 00053_053_SN01_15bars_ramp2.csv
 - 00054_054_SN01_15bars_ramp3.csv
 - 00055_055_SN01_15bars_ramp4.csv
 - 00056_056_SN01_15bars_onmod.csv
 - 00057_057_SN01_15bars_offmod.csv
 - 00058_058_SN01_15bars_random_short.csv
 - 00059_059_SN01_15bars_random_long.csv
 - 00060_060_SN01_15bars_random_mixed.csv
 - 00061_061_SN01_12bars_ramp1.csv
 - 00062_062_SN01_12bars_ramp2.csv
 - 00063_063_SN01_12bars_ramp3.csv
 - 00064_064_SN01_12bars_ramp4.csv
 - 00065_065_SN01_12bars_onmod.csv
 - 00066_066_SN01_12bars_offmod.csv
 - 00067_067_SN01_12bars_random_short.csv
 - 00068_068_SN01_12bars_random_long.csv
 - 00069_069_SN01_12bars_random_mixed.csv
 - 00070_070_SN01_9bars_ramp1.csv
 - 00071_071_SN01_9bars_ramp2.csv
 - 00072_072_SN01_9bars_ramp3.csv
 - 00073_073_SN01_9bars_ramp4.csv
 - 00074_074_SN01_9bars_onmod.csv
 - 00075_075_SN01_9bars_offmod.csv
 - 00076_076_SN01_9bars_random_short.csv
 - 00077_077_SN01_9bars_random_long.csv
 - 00078_078_SN01_9bars_random_mixed.csv
 - 00079_079_SN01_24bars_ssf.csv
 - 00080_080_SN01_21bars_ssf.csv
 - 00081_081_SN01_18bars_ssf.csv
 - 00082_082_SN01_15bars_ssf.csv
 - 00083_083_SN01_12bars_ssf.csv
 - 00084_084_SN01_9bars_ssf.csv
 - 00085_085_SN01_24bars_health_check.csv
 - 00086_086_SN01_21bars_health_check.csv
 - 00087_087_SN01_18bars_health_check.csv
 - 00088_088_SN01_15bars_health_check.csv
 - 00089_089_SN01_12bars_health_check.csv
 - 00090_090_SN01_9bars_health_check.csv
 - 00091_091_SN01_7bars_ssf.csv
 - 00092_092_SN01_5bars_ssf.csv
 - 00093_093_SN01_7bars_health_check.csv
 - 00094_094_SN01_5bars_health_check.csv
 - 00095_095_SN01_7bars_ramp1.csv
 - 00096_096_SN01_7bars_ramp2.csv
 - 00097_097_SN01_7bars_ramp3.csv
 - 00098_098_SN01_7bars_ramp4.csv
 - 00099_099_SN01_7bars_onmod.csv
 - 00100_100_SN01_7bars_offmod.csv
 - 00101_101_SN01_7bars_random_short.csv
 - 00102_102_SN01_7bars_random_long.csv
 - 00103_103_SN01_7bars_random_mixed.csv
 - 00104_104_SN01_5bars_ramp1.csv
 - 00105_105_SN01_5bars_ramp2.csv
 - 00106_106_SN01_5bars_ramp3.csv
 - 00107_107_SN01_5bars_ramp4.csv
 - 00108_108_SN01_5bars_onmod.csv
 - 00109_109_SN01_5bars_offmod.csv
 - 00110_110_SN01_5bars_random_short.csv
 - 00111_111_SN01_5bars_random_long.csv
 - 00112_112_SN01_5bars_random_mixed.csv
 - 00113_001_SN02_24bars_ssf.csv
 - 00114_002_SN02_21bars_ssf.csv
 - 00115_003_SN02_18bars_ssf.csv
 - 00116_004_SN02_15bars_ssf.csv
 - 00117_005_SN02_12bars_ssf.csv
 - 00118_006_SN02_9bars_ssf.csv
 - 00119_007_SN02_24bars_health_check.csv
 - 00120_008_SN02_21bars_health_check.csv
 - 00121_009_SN02_18bars_health_check.csv
 - 00122_010_SN02_15bars_health_check.csv
 - 00123_011_SN02_12bars_health_check.csv
 - 00124_012_SN02_9bars_health_check.csv
 - 00125_013_SN02_24bars_ramp1.csv
 - 00126_014_SN02_24bars_ramp2.csv
 - 00127_015_SN02_24bars_ramp3.csv
 - 00128_016_SN02_24bars_ramp4.csv
 - 00129_017_SN02_24bars_onmod.csv
 - 00130_018_SN02_24bars_offmod.csv
 - 00131_019_SN02_24bars_random_short.csv
 - 00132_020_SN02_24bars_random_long.csv
 - 00133_021_SN02_24bars_random_mixed.csv
 - 00134_022_SN02_21bars_ramp1.csv
 - 00135_023_SN02_21bars_ramp2.csv
 - 00136_024_SN02_21bars_ramp3.csv
 - 00137_025_SN02_21bars_ramp4.csv
 - 00138_026_SN02_21bars_onmod.csv
 - 00139_027_SN02_21bars_offmod.csv
 - 00140_028_SN02_21bars_random_short.csv
 - 00141_029_SN02_21bars_random_long.csv
 - 00142_030_SN02_21bars_random_mixed.csv
 - 00143_031_SN02_18bars_ramp1.csv
 - 00144_032_SN02_18bars_ramp2.csv
 - 00145_033_SN02_18bars_ramp3.csv
 - 00146_034_SN02_18bars_ramp4.csv
 - 00147_035_SN02_18bars_onmod.csv
 - 00148_036_SN02_18bars_offmod.csv
 - 00149_037_SN02_18bars_random_short.csv
 - 00150_038_SN02_18bars_random_long.csv
 - 00151_039_SN02_18bars_random_mixed.csv
 - 00152_040_SN02_24bars_ssf.csv
 - 00153_041_SN02_21bars_ssf.csv
 - 00154_042_SN02_18bars_ssf.csv
 - 00155_043_SN02_15bars_ssf.csv
 - 00156_044_SN02_12bars_ssf.csv
 - 00157_045_SN02_9bars_ssf.csv
 - 00158_046_SN02_24bars_health_check.csv
 - 00159_047_SN02_21bars_health_check.csv
 - 00160_048_SN02_18bars_health_check.csv
 - 00161_049_SN02_15bars_health_check.csv
 - 00162_050_SN02_12bars_health_check.csv
 - 00163_051_SN02_9bars_health_check.csv
 - 00164_052_SN02_15bars_ramp1.csv
 - 00165_053_SN02_15bars_ramp2.csv
 - 00166_054_SN02_15bars_ramp3.csv
 - 00167_055_SN02_15bars_ramp4.csv
 - 00168_056_SN02_15bars_onmod.csv
 - 00169_057_SN02_15bars_offmod.csv
 - 00170_058_SN02_15bars_random_short.csv
 - 00171_059_SN02_15bars_random_long.csv
 - 00172_060_SN02_15bars_random_mixed.csv
 - 00173_061_SN02_12bars_ramp1.csv
 - 00174_062_SN02_12bars_ramp2.csv
 - 00175_063_SN02_12bars_ramp3.csv
 - 00176_064_SN02_12bars_ramp4.csv
 - 00177_065_SN02_12bars_onmod.csv
 - 00178_066_SN02_12bars_offmod.csv
 - 00179_067_SN02_12bars_random_short.csv
 - 00180_068_SN02_12bars_random_long.csv
 - 00181_069_SN02_12bars_random_mixed.csv
 - 00182_070_SN02_9bars_ramp1.csv
 - 00183_071_SN02_9bars_ramp2.csv
 - 00184_072_SN02_9bars_ramp3.csv
 - 00185_073_SN02_9bars_ramp4.csv
 - 00186_074_SN02_9bars_onmod.csv
 - 00187_075_SN02_9bars_offmod.csv
 - 00188_076_SN02_9bars_random_short.csv
 - 00189_077_SN02_9bars_random_long.csv
 - 00190_078_SN02_9bars_random_mixed.csv
 - 00191_079_SN02_24bars_ssf.csv
 - 00192_080_SN02_21bars_ssf.csv
 - 00193_081_SN02_18bars_ssf.csv
 - 00194_082_SN02_15bars_ssf.csv
 - 00195_083_SN02_12bars_ssf.csv
 - 00196_084_SN02_9bars_ssf.csv
 - 00197_085_SN02_24bars_health_check.csv
 - 00198_086_SN02_21bars_health_check.csv
 - 00199_087_SN02_18bars_health_check.csv
 - 00200_088_SN02_15bars_health_check.csv
 - 00201_089_SN02_12bars_health_check.csv
 - 00202_090_SN02_9bars_health_check.csv
 - 00203_091_SN02_7bars_ssf.csv
 - 00204_092_SN02_5bars_ssf.csv
 - 00205_093_SN02_7bars_health_check.csv
 - 00206_094_SN02_5bars_health_check.csv
 - 00207_095_SN02_7bars_ramp1.csv
 - 00208_096_SN02_7bars_ramp2.csv
 - 00209_097_SN02_7bars_ramp3.csv
 - 00210_098_SN02_7bars_ramp4.csv
 - 00211_099_SN02_7bars_onmod.csv
 - 00212_100_SN02_7bars_offmod.csv
 - 00213_101_SN02_7bars_random_short.csv
 - 00214_102_SN02_7bars_random_long.csv
 - 00215_103_SN02_7bars_random_mixed.csv
 - 00216_104_SN02_5bars_ramp1.csv
 - 00217_105_SN02_5bars_ramp2.csv
 - 00218_106_SN02_5bars_ramp3.csv
 - 00219_107_SN02_5bars_ramp4.csv
 - 00220_108_SN02_5bars_onmod.csv
 - 00221_109_SN02_5bars_offmod.csv
 - 00222_110_SN02_5bars_random_short.csv
 - 00223_111_SN02_5bars_random_long.csv
 - 00224_112_SN02_5bars_random_mixed.csv
 - 00225_001_SN03_24bars_ssf.csv
 - 00226_002_SN03_21bars_ssf.csv
 - 00227_003_SN03_18bars_ssf.csv
 - 00228_004_SN03_15bars_ssf.csv
 - 00229_005_SN03_12bars_ssf.csv
 - 00230_006_SN03_9bars_ssf.csv
 - 00231_007_SN03_24bars_health_check.csv
 - 00232_008_SN03_21bars_health_check.csv
 - 00233_009_SN03_18bars_health_check.csv
 - 00234_010_SN03_15bars_health_check.csv
 - 00235_011_SN03_12bars_health_check.csv
 - 00236_012_SN03_9bars_health_check.csv
 - 00237_013_SN03_24bars_ramp1.csv
 - 00238_014_SN03_24bars_ramp2.csv
 - 00239_015_SN03_24bars_ramp3.csv
 - 00240_016_SN03_24bars_ramp4.csv
 - 00241_017_SN03_24bars_onmod.csv
 - 00242_018_SN03_24bars_offmod.csv
 - 00243_019_SN03_24bars_random_short.csv
 - 00244_020_SN03_24bars_random_long.csv
 - 00245_021_SN03_24bars_random_mixed.csv
 - 00246_022_SN03_21bars_ramp1.csv
 - 00247_023_SN03_21bars_ramp2.csv
 - 00248_024_SN03_21bars_ramp3.csv
 - 00249_025_SN03_21bars_ramp4.csv
 - 00250_026_SN03_21bars_onmod.csv
 - 00251_027_SN03_21bars_offmod.csv
 - 00252_028_SN03_21bars_random_short.csv
 - 00253_029_SN03_21bars_random_long.csv
 - 00254_030_SN03_21bars_random_mixed.csv
 - 00255_031_SN03_18bars_ramp1.csv
 - 00256_032_SN03_18bars_ramp2.csv
 - 00257_033_SN03_18bars_ramp3.csv
 - 00258_034_SN03_18bars_ramp4.csv
 - 00259_035_SN03_18bars_onmod.csv
 - 00260_036_SN03_18bars_offmod.csv
 - 00261_037_SN03_18bars_random_short.csv
 - 00262_038_SN03_18bars_random_long.csv
 - 00263_039_SN03_18bars_random_mixed.csv
 - 00264_040_SN03_24bars_ssf.csv
 - 00265_041_SN03_21bars_ssf.csv
 - 00266_042_SN03_18bars_ssf.csv
 - 00267_043_SN03_15bars_ssf.csv
 - 00268_044_SN03_12bars_ssf.csv
 - 00269_045_SN03_9bars_ssf.csv
 - 00270_046_SN03_24bars_health_check.csv
 - 00271_047_SN03_21bars_health_check.csv
 - 00272_048_SN03_18bars_health_check.csv
 - 00273_049_SN03_15bars_health_check.csv
 - 00274_050_SN03_12bars_health_check.csv
 - 00275_051_SN03_9bars_health_check.csv
 - 00276_052_SN03_15bars_ramp1.csv
 - 00277_053_SN03_15bars_ramp2.csv
 - 00278_054_SN03_15bars_ramp3.csv
 - 00279_055_SN03_15bars_ramp4.csv
 - 00280_056_SN03_15bars_onmod.csv
 - 00281_057_SN03_15bars_offmod.csv
 - 00282_058_SN03_15bars_random_short.csv
 - 00283_059_SN03_15bars_random_long.csv
 - 00284_060_SN03_15bars_random_mixed.csv
 - 00285_061_SN03_12bars_ramp1.csv
 - 00286_062_SN03_12bars_ramp2.csv
 - 00287_063_SN03_12bars_ramp3.csv
 - 00288_064_SN03_12bars_ramp4.csv
 - 00289_065_SN03_12bars_onmod.csv
 - 00290_066_SN03_12bars_offmod.csv
 - 00291_067_SN03_12bars_random_short.csv
 - 00292_068_SN03_12bars_random_long.csv
 - 00293_069_SN03_12bars_random_mixed.csv
 - 00294_070_SN03_9bars_ramp1.csv
 - 00295_071_SN03_9bars_ramp2.csv
 - 00296_072_SN03_9bars_ramp3.csv
 - 00297_073_SN03_9bars_ramp4.csv
 - 00298_074_SN03_9bars_onmod.csv
 - 00299_075_SN03_9bars_offmod.csv
 - 00300_076_SN03_9bars_random_short.csv
 - 00301_077_SN03_9bars_random_long.csv
 - 00302_078_SN03_9bars_random_mixed.csv
 - 00303_079_SN03_24bars_ssf.csv
 - 00304_080_SN03_21bars_ssf.csv
 - 00305_081_SN03_18bars_ssf.csv
 - 00306_082_SN03_15bars_ssf.csv
 - 00307_083_SN03_12bars_ssf.csv
 - 00308_084_SN03_9bars_ssf.csv
 - 00309_085_SN03_24bars_health_check.csv
 - 00310_086_SN03_21bars_health_check.csv
 - 00311_087_SN03_18bars_health_check.csv
 - 00312_088_SN03_15bars_health_check.csv
 - 00313_089_SN03_12bars_health_check.csv
 - 00314_090_SN03_9bars_health_check.csv
 - 00315_091_SN03_7bars_ssf.csv
 - 00316_092_SN03_5bars_ssf.csv
 - 00317_093_SN03_7bars_health_check.csv
 - 00318_094_SN03_5bars_health_check.csv
 - 00319_095_SN03_7bars_ramp1.csv
 - 00320_096_SN03_7bars_ramp2.csv
 - 00321_097_SN03_7bars_ramp3.csv
 - 00322_098_SN03_7bars_ramp4.csv
 - 00323_099_SN03_7bars_onmod.csv
 - 00324_100_SN03_7bars_offmod.csv
 - 00325_101_SN03_7bars_random_short.csv
 - 00326_102_SN03_7bars_random_long.csv
 - 00327_103_SN03_7bars_random_mixed.csv
 - 00328_104_SN03_5bars_ramp1.csv
 - 00329_105_SN03_5bars_ramp2.csv
 - 00330_106_SN03_5bars_ramp3.csv
 - 00331_107_SN03_5bars_ramp4.csv
 - 00332_108_SN03_5bars_onmod.csv
 - 00333_109_SN03_5bars_offmod.csv
 - 00334_110_SN03_5bars_random_short.csv
 - 00335_111_SN03_5bars_random_long.csv
 - 00336_112_SN03_5bars_random_mixed.csv
 - 00337_001_SN04_24bars_ssf.csv
 - 00338_002_SN04_21bars_ssf.csv
 - 00339_003_SN04_18bars_ssf.csv
 - 00340_004_SN04_15bars_ssf.csv
 - 00341_005_SN04_12bars_ssf.csv
 - 00342_006_SN04_9bars_ssf.csv
 - 00343_007_SN04_24bars_health_check.csv
 - 00344_008_SN04_21bars_health_check.csv
 - 00345_009_SN04_18bars_health_check.csv
 - 00346_010_SN04_15bars_health_check.csv
 - 00347_011_SN04_12bars_health_check.csv
 - 00348_012_SN04_9bars_health_check.csv
 - 00349_013_SN04_24bars_ramp1.csv
 - 00350_014_SN04_24bars_ramp2.csv
 - 00351_015_SN04_24bars_ramp3.csv
 - 00352_016_SN04_24bars_ramp4.csv
 - 00353_017_SN04_24bars_onmod.csv
 - 00354_018_SN04_24bars_offmod.csv
 - 00355_019_SN04_24bars_random_short.csv
 - 00356_020_SN04_24bars_random_long.csv
 - 00357_021_SN04_24bars_random_mixed.csv
 - 00358_022_SN04_21bars_ramp1.csv
 - 00359_023_SN04_21bars_ramp2.csv
 - 00360_024_SN04_21bars_ramp3.csv
 - 00361_025_SN04_21bars_ramp4.csv
 - 00362_026_SN04_21bars_onmod.csv
 - 00363_027_SN04_21bars_offmod.csv
 - 00364_028_SN04_21bars_random_short.csv
 - 00365_029_SN04_21bars_random_long.csv
 - 00366_030_SN04_21bars_random_mixed.csv
 - 00367_031_SN04_18bars_ramp1.csv
 - 00368_032_SN04_18bars_ramp2.csv
 - 00369_033_SN04_18bars_ramp3.csv
 - 00370_034_SN04_18bars_ramp4.csv
 - 00371_035_SN04_18bars_onmod.csv
 - 00372_036_SN04_18bars_offmod.csv
 - 00373_037_SN04_18bars_random_short.csv
 - 00374_038_SN04_18bars_random_long.csv
 - 00375_039_SN04_18bars_random_mixed.csv
 - 00376_040_SN04_24bars_ssf.csv
 - 00377_041_SN04_21bars_ssf.csv
 - 00378_042_SN04_18bars_ssf.csv
 - 00379_043_SN04_15bars_ssf.csv
 - 00380_044_SN04_12bars_ssf.csv
 - 00381_045_SN04_9bars_ssf.csv
 - 00382_046_SN04_24bars_health_check.csv
 - 00383_047_SN04_21bars_health_check.csv
 - 00384_048_SN04_18bars_health_check.csv
 - 00385_049_SN04_15bars_health_check.csv
 - 00386_050_SN04_12bars_health_check.csv
 - 00387_051_SN04_9bars_health_check.csv
 - 00388_052_SN04_15bars_ramp1.csv
 - 00389_053_SN04_15bars_ramp2.csv
 - 00390_054_SN04_15bars_ramp3.csv
 - 00391_055_SN04_15bars_ramp4.csv
 - 00392_056_SN04_15bars_onmod.csv
 - 00393_057_SN04_15bars_offmod.csv
 - 00394_058_SN04_15bars_random_short.csv
 - 00395_059_SN04_15bars_random_long.csv
 - 00396_060_SN04_15bars_random_mixed.csv
 - 00397_061_SN04_12bars_ramp1.csv
 - 00398_062_SN04_12bars_ramp2.csv
 - 00399_063_SN04_12bars_ramp3.csv
 - 00400_064_SN04_12bars_ramp4.csv
 - 00401_065_SN04_12bars_onmod.csv
 - 00402_066_SN04_12bars_offmod.csv
 - 00403_067_SN04_12bars_random_short.csv
 - 00404_068_SN04_12bars_random_long.csv
 - 00405_069_SN04_12bars_random_mixed.csv
 - 00406_070_SN04_9bars_ramp1.csv
 - 00407_071_SN04_9bars_ramp2.csv
 - 00408_072_SN04_9bars_ramp3.csv
 - 00409_073_SN04_9bars_ramp4.csv
 - 00410_074_SN04_9bars_onmod.csv
 - 00411_075_SN04_9bars_offmod.csv
 - 00412_076_SN04_9bars_random_short.csv
 - 00413_077_SN04_9bars_random_long.csv
 - 00414_078_SN04_9bars_random_mixed.csv
 - 00415_079_SN04_24bars_ssf.csv
 - 00416_080_SN04_21bars_ssf.csv
 - 00417_081_SN04_18bars_ssf.csv
 - 00418_082_SN04_15bars_ssf.csv
 - 00419_083_SN04_12bars_ssf.csv
 - 00420_084_SN04_9bars_ssf.csv
 - 00421_085_SN04_24bars_health_check.csv
 - 00422_086_SN04_21bars_health_check.csv
 - 00423_087_SN04_18bars_health_check.csv
 - 00424_088_SN04_15bars_health_check.csv
 - 00425_089_SN04_12bars_health_check.csv
 - 00426_090_SN04_9bars_health_check.csv
 - 00427_091_SN04_7bars_ssf.csv
 - 00428_092_SN04_5bars_ssf.csv
 - 00429_093_SN04_7bars_health_check.csv
 - 00430_094_SN04_5bars_health_check.csv
 - 00431_095_SN04_7bars_ramp1.csv
 - 00432_096_SN04_7bars_ramp2.csv
 - 00433_097_SN04_7bars_ramp3.csv
 - 00434_098_SN04_7bars_ramp4.csv
 - 00435_099_SN04_7bars_onmod.csv
 - 00436_100_SN04_7bars_offmod.csv
 - 00437_101_SN04_7bars_random_short.csv
 - 00438_102_SN04_7bars_random_long.csv
 - 00439_103_SN04_7bars_random_mixed.csv
 - 00440_104_SN04_5bars_ramp1.csv
 - 00441_105_SN04_5bars_ramp2.csv
 - 00442_106_SN04_5bars_ramp3.csv
 - 00443_107_SN04_5bars_ramp4.csv
 - 00444_108_SN04_5bars_onmod.csv
 - 00445_109_SN04_5bars_offmod.csv
 - 00446_110_SN04_5bars_random_short.csv
 - 00447_111_SN04_5bars_random_long.csv
 - 00448_112_SN04_5bars_random_mixed.csv
 - 00449_001_SN05_24bars_ssf.csv
 - 00450_002_SN05_21bars_ssf.csv
 - 00451_003_SN05_18bars_ssf.csv
 - 00452_004_SN05_15bars_ssf.csv
 - 00453_005_SN05_12bars_ssf.csv
 - 00454_006_SN05_9bars_ssf.csv
 - 00455_007_SN05_24bars_health_check.csv
 - 00456_008_SN05_21bars_health_check.csv
 - 00457_009_SN05_18bars_health_check.csv
 - 00458_010_SN05_15bars_health_check.csv
 - 00459_011_SN05_12bars_health_check.csv
 - 00460_012_SN05_9bars_health_check.csv
 - 00461_013_SN05_24bars_ramp1.csv
 - 00462_014_SN05_24bars_ramp2.csv
 - 00463_015_SN05_24bars_ramp3.csv
 - 00464_016_SN05_24bars_ramp4.csv
 - 00465_017_SN05_24bars_onmod.csv
 - 00466_018_SN05_24bars_offmod.csv
 - 00467_019_SN05_24bars_random_short.csv
 - 00468_020_SN05_24bars_random_long.csv
 - 00469_021_SN05_24bars_random_mixed.csv
 - 00470_022_SN05_21bars_ramp1.csv
 - 00471_023_SN05_21bars_ramp2.csv
 - 00472_024_SN05_21bars_ramp3.csv
 - 00473_025_SN05_21bars_ramp4.csv
 - 00474_026_SN05_21bars_onmod.csv
 - 00475_027_SN05_21bars_offmod.csv
 - 00476_028_SN05_21bars_random_short.csv
 - 00477_029_SN05_21bars_random_long.csv
 - 00478_030_SN05_21bars_random_mixed.csv
 - 00479_031_SN05_18bars_ramp1.csv
 - 00480_032_SN05_18bars_ramp2.csv
 - 00481_033_SN05_18bars_ramp3.csv
 - 00482_034_SN05_18bars_ramp4.csv
 - 00483_035_SN05_18bars_onmod.csv
 - 00484_036_SN05_18bars_offmod.csv
 - 00485_037_SN05_18bars_random_short.csv
 - 00486_038_SN05_18bars_random_long.csv
 - 00487_039_SN05_18bars_random_mixed.csv
 - 00488_040_SN05_24bars_ssf.csv
 - 00489_041_SN05_21bars_ssf.csv
 - 00490_042_SN05_18bars_ssf.csv
 - 00491_043_SN05_15bars_ssf.csv
 - 00492_044_SN05_12bars_ssf.csv
 - 00493_045_SN05_9bars_ssf.csv
 - 00494_046_SN05_24bars_health_check.csv
 - 00495_047_SN05_21bars_health_check.csv
 - 00496_048_SN05_18bars_health_check.csv
 - 00497_049_SN05_15bars_health_check.csv
 - 00498_050_SN05_12bars_health_check.csv
 - 00499_051_SN05_9bars_health_check.csv
 - 00500_052_SN05_15bars_ramp1.csv
 - 00501_053_SN05_15bars_ramp2.csv
 - 00502_054_SN05_15bars_ramp3.csv
 - 00503_055_SN05_15bars_ramp4.csv
 - 00504_056_SN05_15bars_onmod.csv
 - 00505_057_SN05_15bars_offmod.csv
 - 00506_058_SN05_15bars_random_short.csv
 - 00507_059_SN05_15bars_random_long.csv
 - 00508_060_SN05_15bars_random_mixed.csv
 - 00509_061_SN05_12bars_ramp1.csv
 - 00510_062_SN05_12bars_ramp2.csv
 - 00511_063_SN05_12bars_ramp3.csv
 - 00512_064_SN05_12bars_ramp4.csv
 - 00513_065_SN05_12bars_onmod.csv
 - 00514_066_SN05_12bars_offmod.csv
 - 00515_067_SN05_12bars_random_short.csv
 - 00516_068_SN05_12bars_random_long.csv
 - 00517_069_SN05_12bars_random_mixed.csv
 - 00518_070_SN05_9bars_ramp1.csv
 - 00519_071_SN05_9bars_ramp2.csv
 - 00520_072_SN05_9bars_ramp3.csv
 - 00521_073_SN05_9bars_ramp4.csv
 - 00522_074_SN05_9bars_onmod.csv
 - 00523_075_SN05_9bars_offmod.csv
 - 00524_076_SN05_9bars_random_short.csv
 - 00525_077_SN05_9bars_random_long.csv
 - 00526_078_SN05_9bars_random_mixed.csv
 - 00527_079_SN05_24bars_ssf.csv
 - 00528_080_SN05_21bars_ssf.csv
 - 00529_081_SN05_18bars_ssf.csv
 - 00530_082_SN05_15bars_ssf.csv
 - 00531_083_SN05_12bars_ssf.csv

### Initial Exploratory Data Analysis (EDA)

Now that all raw CSV files are verified and organized into `data/raw/train` and `data/raw/test`, we begin with initial EDA.  
In this section we will:

- Load all CSVs into unified train/test DataFrames  
- Inspect basic structure (`head`, `info`)  
- Check missing values  
- Identify key sensor channels  
- Confirm time ordering and consistency  

This helps determine preprocessing decisions like scaling, window size, and feature selection.

In [5]:
import pandas as pd
import glob
import os

RAW_TRAIN_DIR = r"C:\Users\aymisxx\Documents\GitHub\ProphetLSTM-GAN\data\raw\train"
RAW_TEST_DIR  = r"C:\Users\aymisxx\Documents\GitHub\ProphetLSTM-GAN\data\raw\test"

def load_all_csvs(directory):
    filepaths = sorted(glob.glob(os.path.join(directory, "*.csv")))
    dfs = []
    for fp in filepaths:
        df = pd.read_csv(fp)
        df["source_file"] = os.path.basename(fp)  # keep track
        dfs.append(df)
    full_df = pd.concat(dfs, ignore_index=True)
    return full_df, filepaths

train_df, train_files = load_all_csvs(RAW_TRAIN_DIR)
test_df,  test_files  = load_all_csvs(RAW_TEST_DIR)

train_df.shape, test_df.shape

((81180322, 7), (86104752, 7))

### 2. Initial Exploratory Data Analysis (EDA)

Now that all training and test CSV files have been concatenated into `train_df` and `test_df`, we perform a first-pass EDA to understand the structure of the dataset.

In this section we will:
- Preview a few rows of the training data
- Inspect the column names and data types
- Check for obvious missing values on a sample
- Verify that the additional `source_file` column is correctly attached

This will guide later decisions about feature selection, scaling, and window generation.

In [6]:
# Quick peek at the combined training DataFrame
train_df.head()

,time,ton,thrust,mfr,vl,anomaly_code,source_file
0,2021-01-18 08:00:00.000,0,-0.003521,0.0,0.0,NaN,00001_001_SN01_24bars_ssf.csv
1,2021-01-18 08:00:00.010,0,-0.000250,0.0,0.0,NaN,00001_001_SN01_24bars_ssf.csv
2,2021-01-18 08:00:00.020,0,-0.002765,0.0,0.0,NaN,00001_001_SN01_24bars_ssf.csv
3,2021-01-18 08:00:00.030,0,0.000846,0.0,0.0,NaN,00001_001_SN01_24bars_ssf.csv
4,2021-01-18 08:00:00.040,0,0.003115,0.0,0.0,NaN,00001_001_SN01_24bars_ssf.csv

#### 2.1 Preview of training data

The table above should show:
- One row per time step (or sample) from the rocket sensor data
- A total of 7 columns (6 original sensor/metadata columns + 1 `source_file` column)
- The `source_file` column indicating which original CSV the row came from

We use this to confirm that the concatenation worked correctly and that no unexpected columns appeared.

In [7]:
# List all columns available in the training DataFrame
train_df.columns.tolist()

['time', 'ton', 'thrust', 'mfr', 'vl', 'anomaly_code', 'source_file']

#### 2.2 Column names

The list above tells us which signals and metadata are available.

Typical expectations (depending on dataset specification):
- One or more time-related or index columns
- Several sensor measurements (e.g., pressures, mass flow, temperatures, etc.)
- The added `source_file` column (string), indicating the originating CSV

We will later decide:
- Which columns are used as time-series features
- Whether we need to drop any identifier/index columns before modeling

In [8]:
# Inspect data types of each column
train_df.dtypes

time             object
ton               int64
thrust          float64
mfr             float64
vl              float64
anomaly_code    float64
source_file      object
dtype: object

#### 2.3 Data types

Here we verify that:
- Sensor channels are stored as numeric types (`float64` / `int64`)
- The `source_file` column is of type `object` (string)
- No unexpected non-numeric types exist in feature columns

If any numeric-looking column is stored as `object`, we may need to:
- Clean up formatting (e.g., commas, stray characters)
- Convert it using `pd.to_numeric(..., errors="coerce")` in a later preprocessing step.

In [9]:
# Check missing values on a random sample to avoid heavy computation
sample_size = 200_000  # adjust down if memory is tight

train_sample = train_df.sample(n=sample_size, random_state=42)
train_sample.isna().sum()

time                 0
ton                  0
thrust               0
mfr                  0
vl                   0
anomaly_code    198803
source_file          0
dtype: int64

### 2.X Missing Values Analysis

The table above shows the number of missing values for each column in a sampled subset of the
training dataset.

#### Key observations:

1. **`time`**, **`ton`**, **`thrust`**, **`mfr`**, **`vl`**, and **`source_file`**  
   all have **zero** missing values in the sample.  
   This confirms that the essential time-series sensor channels are complete and consistent.

2. **`anomaly_code`** has a large number of missing values.  
   This is **expected** and **correct**, because:
   - In this dataset, **NaN = normal operation**  
   - A numeric value (e.g., `1–31`) indicates a fault/anomaly type
   - Most thruster sequences are nominal, so the majority of rows naturally contain `NaN`

3. This behavior matches the description in the dataset documentation and aligns with the
   common structure of unsupervised anomaly detection datasets, where:
   - The model trains primarily on **normal data**
   - Anomaly labels are sparse and optional during evaluation

#### Conclusion

The dataset shows clean sensor channels with no missing data in the core numerical features.
`anomaly_code` will **not** be used for training the generative model, but it will be extremely
useful later during evaluation to measure detection accuracy.

Overall, the missing-value profile is exactly what we expect at this stage.

## 3. Time column conversion and ordering

The `time` column is currently stored as a string.  
We convert it to a proper `datetime` type so that:

- We can verify correct ordering within each firing sequence  
- We can detect any discontinuities or strange patterns  
- We can safely drop it later after extracting windowed features

Generative models do not directly use timestamps, so `time` will not be part of the final feature set.

In [10]:
# Convert time column to pandas datetime
train_df['time'] = pd.to_datetime(train_df['time'], errors='coerce')
test_df['time'] = pd.to_datetime(test_df['time'], errors='coerce')

train_df['time'].dtype, test_df['time'].dtype

(dtype('<M8[ns]'), dtype('<M8[ns]'))

### 4. Per-file time ordering check

We verify that each individual sequence (each CSV file) is already sorted by time.
If any sequence is out of order, we will sort it before windowing.

In [11]:
# Check ordering for first 5 files
for i, fn in enumerate(train_df['source_file'].unique()[:5]):
    subset = train_df[train_df['source_file'] == fn]
    ordered = subset['time'].is_monotonic_increasing
    print(f"{fn} → {'OK' if ordered else 'NOT ORDERED'}")

00001_001_SN01_24bars_ssf.csv → OK
00002_002_SN01_21bars_ssf.csv → OK
00003_003_SN01_18bars_ssf.csv → OK
00004_004_SN01_15bars_ssf.csv → OK
00005_005_SN01_12bars_ssf.csv → OK

### 5. Selecting model input features

Now that the dataset structure is verified, we select the columns that will serve as
inputs to the LSTM/GAN model.

We keep the core numerical sensor measurements:

- `thrust`
- `mfr`
- `vl`
- `ton`

These represent the dynamic behavior of the thruster system and are well-suited for
reconstruction-based anomaly detection.

The following columns are dropped from the model input:

- `time` (used for ordering checks only)
- `source_file` (metadata)
- `anomaly_code` (used later for evaluation metrics, not training)

In [12]:
FEATURE_COLS = ['thrust', 'mfr', 'vl', 'ton']
TARGET_COL = 'anomaly_code'  # for evaluation only

# Create feature-only DataFrames
train_features = train_df[FEATURE_COLS].copy()
test_features  = test_df[FEATURE_COLS].copy()

train_features.head()

     thrust  mfr   vl  ton
0 -0.003521  0.0  0.0    0
1 -0.000250  0.0  0.0    0
2 -0.002765  0.0  0.0    0
3  0.000846  0.0  0.0    0
4  0.003115  0.0  0.0    0

### 6. Normalization / Scaling

Neural networks such as LSTMs and GANs require normalized inputs for stable training.  
Since the dataset is extremely large, directly fitting a scaler on the full
`train_features` DataFrame would be slow and memory-intensive.

We instead:
1. Randomly sample a small subset of the training data (e.g., 200k rows)
2. Fit the scaler on this subset
3. Apply the scaler to the entire dataset in efficient chunks

In [13]:
from sklearn.preprocessing import StandardScaler
import numpy as np

# sampling ~200k rows for scaler fit
scaler_sample = train_features.sample(200_000, random_state=42)

scaler = StandardScaler()
scaler.fit(scaler_sample)

print("Scaler fitted on sample.")

Scaler fitted on sample.

In [14]:
def scale_in_chunks(df, scaler, chunk_size=500_000):
    scaled_parts = []
    total = len(df)
    
    for start in range(0, total, chunk_size):
        end = min(start + chunk_size, total)
        chunk = df.iloc[start:end]
        chunk_scaled = scaler.transform(chunk)
        scaled_parts.append(chunk_scaled)
    
    return np.vstack(scaled_parts)

train_scaled = scale_in_chunks(train_features, scaler)
test_scaled  = scale_in_chunks(test_features, scaler)

train_scaled.shape, test_scaled.shape

((81180322, 4), (86104752, 4))

## 7. Sliding-window generator (from normalized time series to fixed windows)

**Goal.**  
Our scaled dataset currently consists of very long time-series sequences of rocket engine sensor data:
- Each CSV file corresponds to one *run* of the engine (one `source_file`).
- After preprocessing and scaling, we have two big arrays:
  - `train_scaled` with shape `(N_train_timesteps, n_features)`
  - `test_scaled` with shape `(N_test_timesteps, n_features)`
- The rows are still in chronological order, and consecutive blocks of rows belong to each original CSV (`source_file`).

Deep learning models like LSTMs and GANs typically operate on **fixed-length sequences** instead of arbitrarily long time series.  
To feed the models, we need to transform each long sequence into many overlapping **sliding windows**.

### What is a sliding window?

Given a 2D time series `X` of shape `(T, F)`:

- `T` = number of timesteps in that sequence
- `F` = number of features (e.g. thrust, mass flow rate, etc.)

We choose:
- a **window length** `W` (e.g. 128 samples)
- a **stride** `S` (e.g. 5 samples between window starts)

Then we create windows:

\[
\text{window}_0 = X[0 : 0+W] \\
\text{window}_1 = X[S : S+W] \\
\text{window}_2 = X[2S : 2S+W] \\
\ldots
\]

Each window has shape `(W, F)`. Stacking all windows from a sequence gives an array of shape:

\[
(\text{num\_windows}, W, F)
\]

### Why we also subsample windows

This dataset is **very large** (tens of millions of rows).  
If we naively create *all possible* windows for every file with small stride, we would end up with **tens of millions of windows**, which would be too large to store in memory.

To keep the problem tractable while still covering a wide range of behaviors:

- We will generate windows **per file** (per `source_file`), preserving temporal order.
- We will **subsample** windows by:
  - using a fixed stride (e.g. `S = 5`),
  - and limiting to at most `MAX_WINDOWS_PER_FILE` windows per file (e.g. 300).

This gives us:
- A large but manageable number of windows,
- Balanced coverage across different engine runs (different `source_file` IDs, pressures, regimes),
- A final tensor `X_train` with shape roughly:

\[
\text{(total\_files)} \times \text{MAX\_WINDOWS\_PER\_FILE} \times W \times F
\]

### This cell

In the next code cell, we will:

1. Define some configuration parameters:
   - `WINDOW_SIZE` (sequence length),
   - `WINDOW_STRIDE` (step between windows),
   - `MAX_WINDOWS_PER_FILE` (to cap memory usage).
2. Implement a helper function that:
   - takes a single 2D NumPy array for one sequence `(T, F)`,
   - returns a stacked array of sliding windows of shape `(num_windows, W, F)`,
   - optionally truncates to at most `MAX_WINDOWS_PER_FILE` windows.

In [15]:
import numpy as np

# Sliding-window configuration
WINDOW_SIZE = 128       # length of each window (timesteps)
WINDOW_STRIDE = 5       # step between consecutive window starts
MAX_WINDOWS_PER_FILE = 300  # cap on number of windows per file to control memory

def make_sliding_windows(sequence_array: np.ndarray,
                         window_size: int = WINDOW_SIZE,
                         stride: int = WINDOW_STRIDE,
                         max_windows_per_file: int = MAX_WINDOWS_PER_FILE) -> np.ndarray:
    """
    Given a 2D array for a single time-series sequence (T x F),
    generate overlapping sliding windows of shape (num_windows x window_size x F).

    Parameters
    ----------
    sequence_array : np.ndarray
        Input array of shape (T, F), already scaled/normalized.
    window_size : int
        Length of each sliding window (number of timesteps).
    stride : int
        Step between starting indices of consecutive windows.
    max_windows_per_file : int
        Maximum number of windows to keep per file. If the raw number
        of windows exceeds this cap, we truncate to the first N windows.

    Returns
    -------
    windows : np.ndarray
        Array of shape (num_windows, window_size, F), dtype float32.
    """
    if sequence_array.ndim != 2:
        raise ValueError(f"Expected 2D array (T, F), got shape {sequence_array.shape}")

    T, F = sequence_array.shape

    if T < window_size:
        # Not enough timesteps to form a single full window
        return np.empty((0, window_size, F), dtype=np.float32)

    # Compute all valid starting indices for windows
    starts = np.arange(0, T - window_size + 1, stride, dtype=np.int64)

    # Optionally cap the number of windows to avoid huge memory usage
    if max_windows_per_file is not None and len(starts) > max_windows_per_file:
        starts = starts[:max_windows_per_file]

    # Build windows by slicing [start : start + window_size] for each start
    # This uses a Python loop, which is simple and explicit. With our cap on
    # windows per file, this remains tractable.
    window_list = []
    for s in starts:
        window = sequence_array[s : s + window_size, :]
        window_list.append(window)

    if not window_list:
        return np.empty((0, window_size, F), dtype=np.float32)

    windows = np.stack(window_list, axis=0).astype(np.float32)
    print(f"Created {windows.shape[0]} windows of shape {windows.shape[1:]} from sequence of length {T}")
    return windows

In [18]:
# Error Test

dummy = np.random.randn(1000, 4)
make_sliding_windows(dummy).shape

Created 175 windows of shape (128, 4) from sequence of length 1000

(175, 128, 4)

### 7.1 Generating windows per sequence (per source file)

We now apply the sliding-window generator to each firing sequence individually.

Why per sequence?
- The dataset was originally split into ~2600 CSV files.
- Each file corresponds to one complete engine run.
- Windows must **not** cross file boundaries, or the model will see artificial transitions.

Procedure:
1. Identify all unique `source_file` values.
2. For each file:
   - Extract its corresponding slice from the scaled matrix.
   - Run `make_sliding_windows` on the slice.
   - Append the resulting windows to a growing list.
3. At the end, stack all window arrays into a single `X_train` array.

We also apply the same procedure for the test split.

In [19]:
from tqdm import tqdm

# Get unique source files from the train set
train_files_unique = train_df['source_file'].unique()

X_train_windows = []

print("Generating train windows...")
for fn in tqdm(train_files_unique):
    # Get indices belonging to this file
    idx = train_df.index[train_df['source_file'] == fn].to_numpy()

    # Extract corresponding rows from scaled array
    seq_array = train_scaled[idx]

    # Make sliding windows
    w = make_sliding_windows(seq_array)

    if len(w) > 0:
        X_train_windows.append(w)

# Concatenate all windows
if X_train_windows:
    X_train = np.concatenate(X_train_windows, axis=0)
else:
    X_train = np.empty((0, WINDOW_SIZE, len(FEATURE_COLS)), dtype=np.float32)

X_train.shape

Generating train windows...

  0%|                                                                                 | 1/1267 [00:02<59:44,  2.83s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

  0%|▏                                                                                | 2/1267 [00:05<56:42,  2.69s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

  0%|▏                                                                                | 3/1267 [00:08<57:21,  2.72s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

  0%|▎                                                                                | 4/1267 [00:10<56:17,  2.67s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

  0%|▎                                                                                | 5/1267 [00:13<56:31,  2.69s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

  0%|▍                                                                                | 6/1267 [00:16<56:19,  2.68s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

  1%|▍                                                                                | 7/1267 [00:18<56:42,  2.70s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

  1%|▌                                                                                | 8/1267 [00:21<56:37,  2.70s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

  1%|▌                                                                                | 9/1267 [00:24<56:56,  2.72s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

  1%|▋                                                                               | 10/1267 [00:27<56:58,  2.72s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

  1%|▋                                                                               | 11/1267 [00:29<56:44,  2.71s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

  1%|▊                                                                               | 12/1267 [00:32<56:46,  2.71s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

  1%|▊                                                                               | 13/1267 [00:35<56:48,  2.72s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

  1%|▉                                                                               | 14/1267 [00:37<56:22,  2.70s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

  1%|▉                                                                               | 15/1267 [00:40<55:56,  2.68s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

  1%|█                                                                               | 16/1267 [00:43<56:17,  2.70s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

  1%|█                                                                               | 17/1267 [00:45<56:10,  2.70s/it]

Created 300 windows of shape (128, 4) from sequence of length 222583

  1%|█▏                                                                              | 18/1267 [00:48<56:00,  2.69s/it]

Created 300 windows of shape (128, 4) from sequence of length 153377

  1%|█▏                                                                              | 19/1267 [00:51<56:00,  2.69s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

  2%|█▎                                                                              | 20/1267 [00:53<55:47,  2.68s/it]

Created 300 windows of shape (128, 4) from sequence of length 109000

  2%|█▎                                                                              | 21/1267 [00:56<55:51,  2.69s/it]

Created 300 windows of shape (128, 4) from sequence of length 30998

  2%|█▍                                                                              | 22/1267 [00:59<55:59,  2.70s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

  2%|█▍                                                                              | 23/1267 [01:02<56:01,  2.70s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

  2%|█▌                                                                              | 24/1267 [01:04<56:08,  2.71s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

  2%|█▌                                                                              | 25/1267 [01:07<55:36,  2.69s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

  2%|█▋                                                                              | 26/1267 [01:10<55:57,  2.71s/it]

Created 300 windows of shape (128, 4) from sequence of length 235419

  2%|█▋                                                                              | 27/1267 [01:13<56:21,  2.73s/it]

Created 300 windows of shape (128, 4) from sequence of length 149607

  2%|█▊                                                                              | 28/1267 [01:15<56:08,  2.72s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

  2%|█▊                                                                              | 29/1267 [01:18<56:45,  2.75s/it]

Created 300 windows of shape (128, 4) from sequence of length 100600

  2%|█▉                                                                              | 30/1267 [01:21<56:33,  2.74s/it]

Created 300 windows of shape (128, 4) from sequence of length 32098

  2%|█▉                                                                              | 31/1267 [01:23<56:24,  2.74s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

  3%|██                                                                              | 32/1267 [01:26<56:16,  2.73s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

  3%|██                                                                              | 33/1267 [01:29<56:45,  2.76s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

  3%|██▏                                                                             | 34/1267 [01:32<57:02,  2.78s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

  3%|██▏                                                                             | 35/1267 [01:35<56:36,  2.76s/it]

Created 300 windows of shape (128, 4) from sequence of length 230313

  3%|██▎                                                                             | 36/1267 [01:37<55:55,  2.73s/it]

Created 300 windows of shape (128, 4) from sequence of length 150182

  3%|██▎                                                                             | 37/1267 [01:40<55:32,  2.71s/it]

Created 300 windows of shape (128, 4) from sequence of length 30592

  3%|██▍                                                                             | 38/1267 [01:43<55:48,  2.72s/it]

Created 300 windows of shape (128, 4) from sequence of length 96100

  3%|██▍                                                                             | 39/1267 [01:45<55:43,  2.72s/it]

Created 300 windows of shape (128, 4) from sequence of length 32898

  3%|██▌                                                                             | 40/1267 [01:48<55:51,  2.73s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

  3%|██▌                                                                             | 41/1267 [01:51<55:09,  2.70s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

  3%|██▋                                                                             | 42/1267 [01:53<54:36,  2.67s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

  3%|██▋                                                                             | 43/1267 [01:56<54:36,  2.68s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

  3%|██▊                                                                             | 44/1267 [01:59<54:42,  2.68s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

  4%|██▊                                                                             | 45/1267 [02:01<54:38,  2.68s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

  4%|██▉                                                                             | 46/1267 [02:04<54:53,  2.70s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

  4%|██▉                                                                             | 47/1267 [02:07<54:34,  2.68s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

  4%|███                                                                             | 48/1267 [02:09<54:39,  2.69s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

  4%|███                                                                             | 49/1267 [02:12<54:24,  2.68s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

  4%|███▏                                                                            | 50/1267 [02:15<54:27,  2.68s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

  4%|███▏                                                                            | 51/1267 [02:18<54:38,  2.70s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

  4%|███▎                                                                            | 52/1267 [02:20<55:09,  2.72s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

  4%|███▎                                                                            | 53/1267 [02:23<55:36,  2.75s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

  4%|███▍                                                                            | 54/1267 [02:26<55:46,  2.76s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

  4%|███▍                                                                            | 55/1267 [02:29<55:39,  2.76s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

  4%|███▌                                                                            | 56/1267 [02:31<55:20,  2.74s/it]

Created 300 windows of shape (128, 4) from sequence of length 226896

  4%|███▌                                                                            | 57/1267 [02:34<54:48,  2.72s/it]

Created 300 windows of shape (128, 4) from sequence of length 147189

  5%|███▋                                                                            | 58/1267 [02:37<54:23,  2.70s/it]

Created 300 windows of shape (128, 4) from sequence of length 30592

  5%|███▋                                                                            | 59/1267 [02:39<54:02,  2.68s/it]

Created 300 windows of shape (128, 4) from sequence of length 110400

  5%|███▊                                                                            | 60/1267 [02:42<53:44,  2.67s/it]

Created 300 windows of shape (128, 4) from sequence of length 21997

  5%|███▊                                                                            | 61/1267 [02:45<53:38,  2.67s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

  5%|███▉                                                                            | 62/1267 [02:47<53:52,  2.68s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

  5%|███▉                                                                            | 63/1267 [02:50<53:40,  2.67s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

  5%|████                                                                            | 64/1267 [02:53<53:35,  2.67s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

  5%|████                                                                            | 65/1267 [02:55<53:32,  2.67s/it]

Created 300 windows of shape (128, 4) from sequence of length 229185

  5%|████▏                                                                           | 66/1267 [02:58<52:55,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 150429

  5%|████▏                                                                           | 67/1267 [03:01<53:01,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 30592

  5%|████▎                                                                           | 68/1267 [03:03<53:00,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 107700

  5%|████▎                                                                           | 69/1267 [03:06<52:55,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 21497

  6%|████▍                                                                           | 70/1267 [03:09<53:03,  2.66s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

  6%|████▍                                                                           | 71/1267 [03:11<53:13,  2.67s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

  6%|████▌                                                                           | 72/1267 [03:14<53:12,  2.67s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

  6%|████▌                                                                           | 73/1267 [03:17<52:55,  2.66s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

  6%|████▋                                                                           | 74/1267 [03:19<53:10,  2.67s/it]

Created 300 windows of shape (128, 4) from sequence of length 228869

  6%|████▋                                                                           | 75/1267 [03:22<53:19,  2.68s/it]

Created 300 windows of shape (128, 4) from sequence of length 151281

  6%|████▊                                                                           | 76/1267 [03:25<53:08,  2.68s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

  6%|████▊                                                                           | 77/1267 [03:27<52:33,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 106600

  6%|████▉                                                                           | 78/1267 [03:30<52:08,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 25298

  6%|████▉                                                                           | 79/1267 [03:33<52:11,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

  6%|█████                                                                           | 80/1267 [03:35<52:04,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

  6%|█████                                                                           | 81/1267 [03:38<51:38,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

  6%|█████▏                                                                          | 82/1267 [03:40<50:48,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

  7%|█████▏                                                                          | 83/1267 [03:43<50:49,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

  7%|█████▎                                                                          | 84/1267 [03:45<50:44,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

  7%|█████▎                                                                          | 85/1267 [03:48<50:48,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

  7%|█████▍                                                                          | 86/1267 [03:51<50:45,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

  7%|█████▍                                                                          | 87/1267 [03:53<50:41,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

  7%|█████▌                                                                          | 88/1267 [03:56<51:04,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

  7%|█████▌                                                                          | 89/1267 [03:58<50:50,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

  7%|█████▋                                                                          | 90/1267 [04:01<50:38,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

  7%|█████▋                                                                          | 91/1267 [04:03<50:36,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

  7%|█████▊                                                                          | 92/1267 [04:06<50:41,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

  7%|█████▊                                                                          | 93/1267 [04:09<51:09,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

  7%|█████▉                                                                          | 94/1267 [04:11<51:10,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

  7%|█████▉                                                                          | 95/1267 [04:14<51:18,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

  8%|██████                                                                          | 96/1267 [04:17<51:24,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

  8%|██████                                                                          | 97/1267 [04:19<51:10,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

  8%|██████▏                                                                         | 98/1267 [04:22<51:24,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

  8%|██████▎                                                                         | 99/1267 [04:25<51:38,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 228886

  8%|██████▏                                                                        | 100/1267 [04:27<52:04,  2.68s/it]

Created 300 windows of shape (128, 4) from sequence of length 150590

  8%|██████▎                                                                        | 101/1267 [04:30<51:45,  2.66s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

  8%|██████▎                                                                        | 102/1267 [04:33<51:22,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 111100

  8%|██████▍                                                                        | 103/1267 [04:35<51:26,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 21097

  8%|██████▍                                                                        | 104/1267 [04:38<50:25,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

  8%|██████▌                                                                        | 105/1267 [04:40<50:10,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

  8%|██████▌                                                                        | 106/1267 [04:43<50:03,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

  8%|██████▋                                                                        | 107/1267 [04:45<49:42,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

  9%|██████▋                                                                        | 108/1267 [04:48<49:40,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 225461

  9%|██████▊                                                                        | 109/1267 [04:51<49:58,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 147848

  9%|██████▊                                                                        | 110/1267 [04:53<50:10,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

  9%|██████▉                                                                        | 111/1267 [04:56<49:49,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 102800

  9%|██████▉                                                                        | 112/1267 [04:58<50:13,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 27997

  9%|███████                                                                        | 113/1267 [05:01<50:03,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

  9%|███████                                                                        | 114/1267 [05:04<49:25,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

  9%|███████▏                                                                       | 115/1267 [05:06<49:59,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

  9%|███████▏                                                                       | 116/1267 [05:09<49:07,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

  9%|███████▎                                                                       | 117/1267 [05:11<49:32,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

  9%|███████▎                                                                       | 118/1267 [05:14<49:12,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

  9%|███████▍                                                                       | 119/1267 [05:16<49:22,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

  9%|███████▍                                                                       | 120/1267 [05:19<49:50,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 10%|███████▌                                                                       | 121/1267 [05:22<49:44,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 10%|███████▌                                                                       | 122/1267 [05:24<49:37,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 10%|███████▋                                                                       | 123/1267 [05:27<50:12,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 10%|███████▋                                                                       | 124/1267 [05:30<49:48,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 10%|███████▊                                                                       | 125/1267 [05:32<50:00,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 10%|███████▊                                                                       | 126/1267 [05:35<50:35,  2.66s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 10%|███████▉                                                                       | 127/1267 [05:38<50:09,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 10%|███████▉                                                                       | 128/1267 [05:40<49:41,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 10%|████████                                                                       | 129/1267 [05:43<49:17,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 222583

 10%|████████                                                                       | 130/1267 [05:45<48:58,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 153377

 10%|████████▏                                                                      | 131/1267 [05:48<48:43,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 10%|████████▏                                                                      | 132/1267 [05:50<48:47,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 109000

 10%|████████▎                                                                      | 133/1267 [05:53<48:42,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 30998

 11%|████████▎                                                                      | 134/1267 [05:56<48:49,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 11%|████████▍                                                                      | 135/1267 [05:58<48:53,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 11%|████████▍                                                                      | 136/1267 [06:01<48:32,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 11%|████████▌                                                                      | 137/1267 [06:03<48:18,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 11%|████████▌                                                                      | 138/1267 [06:06<48:31,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 235419

 11%|████████▋                                                                      | 139/1267 [06:08<48:32,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 149607

 11%|████████▋                                                                      | 140/1267 [06:11<48:16,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 11%|████████▊                                                                      | 141/1267 [06:14<48:00,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 100600

 11%|████████▊                                                                      | 142/1267 [06:16<47:52,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 32098

 11%|████████▉                                                                      | 143/1267 [06:19<48:09,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 11%|████████▉                                                                      | 144/1267 [06:21<48:16,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 11%|█████████                                                                      | 145/1267 [06:24<48:03,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 12%|█████████                                                                      | 146/1267 [06:26<48:12,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 12%|█████████▏                                                                     | 147/1267 [06:29<48:18,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 230313

 12%|█████████▏                                                                     | 148/1267 [06:32<48:21,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 150182

 12%|█████████▎                                                                     | 149/1267 [06:34<48:55,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 30592

 12%|█████████▎                                                                     | 150/1267 [06:37<48:43,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 96100

 12%|█████████▍                                                                     | 151/1267 [06:39<48:14,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 32898

 12%|█████████▍                                                                     | 152/1267 [06:42<47:45,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 12%|█████████▌                                                                     | 153/1267 [06:44<47:15,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 12%|█████████▌                                                                     | 154/1267 [06:47<46:59,  2.53s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 12%|█████████▋                                                                     | 155/1267 [06:49<46:38,  2.52s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 12%|█████████▋                                                                     | 156/1267 [06:52<46:24,  2.51s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 12%|█████████▊                                                                     | 157/1267 [06:55<46:35,  2.52s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 12%|█████████▊                                                                     | 158/1267 [06:57<46:45,  2.53s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 13%|█████████▉                                                                     | 159/1267 [07:00<46:44,  2.53s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 13%|█████████▉                                                                     | 160/1267 [07:02<46:59,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 13%|██████████                                                                     | 161/1267 [07:05<47:04,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 13%|██████████                                                                     | 162/1267 [07:07<47:25,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 13%|██████████▏                                                                    | 163/1267 [07:10<47:46,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 13%|██████████▏                                                                    | 164/1267 [07:13<47:46,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 13%|██████████▎                                                                    | 165/1267 [07:15<48:05,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 13%|██████████▎                                                                    | 166/1267 [07:18<48:16,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 13%|██████████▍                                                                    | 167/1267 [07:21<48:29,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 13%|██████████▍                                                                    | 168/1267 [07:23<48:31,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 226896

 13%|██████████▌                                                                    | 169/1267 [07:26<48:03,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 147189

 13%|██████████▌                                                                    | 170/1267 [07:28<47:53,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 30592

 13%|██████████▋                                                                    | 171/1267 [07:31<47:32,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 110400

 14%|██████████▋                                                                    | 172/1267 [07:34<47:25,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 21997

 14%|██████████▊                                                                    | 173/1267 [07:36<47:30,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 14%|██████████▊                                                                    | 174/1267 [07:39<47:26,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 14%|██████████▉                                                                    | 175/1267 [07:41<47:00,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 14%|██████████▉                                                                    | 176/1267 [07:44<46:42,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 14%|███████████                                                                    | 177/1267 [07:47<46:53,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 229185

 14%|███████████                                                                    | 178/1267 [07:49<46:32,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 150429

 14%|███████████▏                                                                   | 179/1267 [07:52<46:17,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 30592

 14%|███████████▏                                                                   | 180/1267 [07:54<46:23,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 107700

 14%|███████████▎                                                                   | 181/1267 [07:57<46:05,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 21497

 14%|███████████▎                                                                   | 182/1267 [07:59<46:05,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 14%|███████████▍                                                                   | 183/1267 [08:02<46:05,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 15%|███████████▍                                                                   | 184/1267 [08:04<46:14,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 15%|███████████▌                                                                   | 185/1267 [08:07<46:25,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 15%|███████████▌                                                                   | 186/1267 [08:10<46:45,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 228869

 15%|███████████▋                                                                   | 187/1267 [08:12<46:57,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 151281

 15%|███████████▋                                                                   | 188/1267 [08:15<47:01,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 15%|███████████▊                                                                   | 189/1267 [08:17<46:55,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 106600

 15%|███████████▊                                                                   | 190/1267 [08:20<47:06,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 25298

 15%|███████████▉                                                                   | 191/1267 [08:23<46:59,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 15%|███████████▉                                                                   | 192/1267 [08:25<46:59,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 15%|████████████                                                                   | 193/1267 [08:28<46:50,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 15%|████████████                                                                   | 194/1267 [08:31<46:42,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 15%|████████████▏                                                                  | 195/1267 [08:33<46:35,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 15%|████████████▏                                                                  | 196/1267 [08:36<46:26,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 16%|████████████▎                                                                  | 197/1267 [08:38<46:12,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 16%|████████████▎                                                                  | 198/1267 [08:41<45:42,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 16%|████████████▍                                                                  | 199/1267 [08:43<45:22,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 16%|████████████▍                                                                  | 200/1267 [08:46<44:58,  2.53s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 16%|████████████▌                                                                  | 201/1267 [08:48<45:30,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 16%|████████████▌                                                                  | 202/1267 [08:51<45:35,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 16%|████████████▋                                                                  | 203/1267 [08:54<45:43,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 16%|████████████▋                                                                  | 204/1267 [08:56<45:44,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 16%|████████████▊                                                                  | 205/1267 [08:59<45:46,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 16%|████████████▊                                                                  | 206/1267 [09:01<46:00,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 16%|████████████▉                                                                  | 207/1267 [09:04<46:11,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 16%|████████████▉                                                                  | 208/1267 [09:07<46:17,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 16%|█████████████                                                                  | 209/1267 [09:09<46:12,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 17%|█████████████                                                                  | 210/1267 [09:12<46:03,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 17%|█████████████▏                                                                 | 211/1267 [09:15<45:52,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 228886

 17%|█████████████▏                                                                 | 212/1267 [09:17<46:31,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 150590

 17%|█████████████▎                                                                 | 213/1267 [09:20<46:26,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 17%|█████████████▎                                                                 | 214/1267 [09:23<46:30,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 111100

 17%|█████████████▍                                                                 | 215/1267 [09:25<46:31,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 21097

 17%|█████████████▍                                                                 | 216/1267 [09:28<46:22,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 17%|█████████████▌                                                                 | 217/1267 [09:31<46:30,  2.66s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 17%|█████████████▌                                                                 | 218/1267 [09:33<46:17,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 17%|█████████████▋                                                                 | 219/1267 [09:36<45:59,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 17%|█████████████▋                                                                 | 220/1267 [09:38<45:35,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 225461

 17%|█████████████▊                                                                 | 221/1267 [09:41<45:31,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 147848

 18%|█████████████▊                                                                 | 222/1267 [09:43<44:46,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 18%|█████████████▉                                                                 | 223/1267 [09:46<44:28,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 102800

 18%|█████████████▉                                                                 | 224/1267 [09:49<44:18,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 27997

 18%|██████████████                                                                 | 225/1267 [09:51<44:27,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 18%|██████████████                                                                 | 226/1267 [09:54<44:00,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 18%|██████████████▏                                                                | 227/1267 [09:56<44:05,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 18%|██████████████▏                                                                | 228/1267 [09:59<43:51,  2.53s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 18%|██████████████▎                                                                | 229/1267 [10:01<43:58,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 18%|██████████████▎                                                                | 230/1267 [10:04<43:45,  2.53s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 18%|██████████████▍                                                                | 231/1267 [10:06<44:23,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 18%|██████████████▍                                                                | 232/1267 [10:09<44:40,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 18%|██████████████▌                                                                | 233/1267 [10:12<45:15,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 18%|██████████████▌                                                                | 234/1267 [10:14<45:11,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 19%|██████████████▋                                                                | 235/1267 [10:17<45:05,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 19%|██████████████▋                                                                | 236/1267 [10:20<44:40,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 19%|██████████████▊                                                                | 237/1267 [10:22<44:42,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 19%|██████████████▊                                                                | 238/1267 [10:25<44:50,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 19%|██████████████▉                                                                | 239/1267 [10:27<44:36,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 19%|██████████████▉                                                                | 240/1267 [10:30<44:27,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 19%|███████████████                                                                | 241/1267 [10:33<44:41,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 222583

 19%|███████████████                                                                | 242/1267 [10:35<44:18,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 153377

 19%|███████████████▏                                                               | 243/1267 [10:38<44:05,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 19%|███████████████▏                                                               | 244/1267 [10:40<43:55,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 109000

 19%|███████████████▎                                                               | 245/1267 [10:43<44:10,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 30998

 19%|███████████████▎                                                               | 246/1267 [10:45<44:05,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 19%|███████████████▍                                                               | 247/1267 [10:48<44:04,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 20%|███████████████▍                                                               | 248/1267 [10:51<44:10,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 20%|███████████████▌                                                               | 249/1267 [10:53<44:33,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 20%|███████████████▌                                                               | 250/1267 [10:56<44:28,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 235419

 20%|███████████████▋                                                               | 251/1267 [10:59<44:16,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 149607

 20%|███████████████▋                                                               | 252/1267 [11:01<43:57,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 20%|███████████████▊                                                               | 253/1267 [11:04<44:13,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 100600

 20%|███████████████▊                                                               | 254/1267 [11:06<44:11,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 32098

 20%|███████████████▉                                                               | 255/1267 [11:09<44:19,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 20%|███████████████▉                                                               | 256/1267 [11:12<44:18,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 20%|████████████████                                                               | 257/1267 [11:14<44:13,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 20%|████████████████                                                               | 258/1267 [11:17<44:02,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 20%|████████████████▏                                                              | 259/1267 [11:20<44:16,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 230313

 21%|████████████████▏                                                              | 260/1267 [11:22<43:59,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 150182

 21%|████████████████▎                                                              | 261/1267 [11:25<43:57,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 30592

 21%|████████████████▎                                                              | 262/1267 [11:27<43:44,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 96100

 21%|████████████████▍                                                              | 263/1267 [11:30<43:54,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 32898

 21%|████████████████▍                                                              | 264/1267 [11:33<43:39,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 21%|████████████████▌                                                              | 265/1267 [11:35<43:46,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 21%|████████████████▌                                                              | 266/1267 [11:38<43:32,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 21%|████████████████▋                                                              | 267/1267 [11:40<43:03,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 21%|████████████████▋                                                              | 268/1267 [11:43<42:28,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 21%|████████████████▊                                                              | 269/1267 [11:45<42:43,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 21%|████████████████▊                                                              | 270/1267 [11:48<42:49,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 21%|████████████████▉                                                              | 271/1267 [11:51<42:57,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 21%|████████████████▉                                                              | 272/1267 [11:53<42:59,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 22%|█████████████████                                                              | 273/1267 [11:56<42:49,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 22%|█████████████████                                                              | 274/1267 [11:58<42:38,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 22%|█████████████████▏                                                             | 275/1267 [12:01<42:39,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 22%|█████████████████▏                                                             | 276/1267 [12:04<42:49,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 22%|█████████████████▎                                                             | 277/1267 [12:06<42:56,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 22%|█████████████████▎                                                             | 278/1267 [12:09<43:13,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 22%|█████████████████▍                                                             | 279/1267 [12:12<43:27,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 22%|█████████████████▍                                                             | 280/1267 [12:14<43:40,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 226896

 22%|█████████████████▌                                                             | 281/1267 [12:17<43:20,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 147189

 22%|█████████████████▌                                                             | 282/1267 [12:20<43:19,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 30592

 22%|█████████████████▋                                                             | 283/1267 [12:22<43:07,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 110400

 22%|█████████████████▋                                                             | 284/1267 [12:25<43:07,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 21997

 22%|█████████████████▊                                                             | 285/1267 [12:27<43:20,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 23%|█████████████████▊                                                             | 286/1267 [12:30<43:38,  2.67s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 23%|█████████████████▉                                                             | 287/1267 [12:33<43:18,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 23%|█████████████████▉                                                             | 288/1267 [12:35<43:28,  2.66s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 23%|██████████████████                                                             | 289/1267 [12:38<43:17,  2.66s/it]

Created 300 windows of shape (128, 4) from sequence of length 229185

 23%|██████████████████                                                             | 290/1267 [12:41<42:46,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 150429

 23%|██████████████████▏                                                            | 291/1267 [12:43<42:23,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 30592

 23%|██████████████████▏                                                            | 292/1267 [12:46<42:07,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 107700

 23%|██████████████████▎                                                            | 293/1267 [12:48<42:15,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 21497

 23%|██████████████████▎                                                            | 294/1267 [12:51<41:55,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 23%|██████████████████▍                                                            | 295/1267 [12:54<42:03,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 23%|██████████████████▍                                                            | 296/1267 [12:56<41:57,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 23%|██████████████████▌                                                            | 297/1267 [12:59<41:53,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 24%|██████████████████▌                                                            | 298/1267 [13:01<42:01,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 228869

 24%|██████████████████▋                                                            | 299/1267 [13:04<42:07,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 151281

 24%|██████████████████▋                                                            | 300/1267 [13:07<41:32,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 24%|██████████████████▊                                                            | 301/1267 [13:09<41:04,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 106600

 24%|██████████████████▊                                                            | 302/1267 [13:12<41:19,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 25298

 24%|██████████████████▉                                                            | 303/1267 [13:14<41:01,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 24%|██████████████████▉                                                            | 304/1267 [13:17<40:48,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 24%|███████████████████                                                            | 305/1267 [13:19<40:53,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 24%|███████████████████                                                            | 306/1267 [13:22<40:41,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 24%|███████████████████▏                                                           | 307/1267 [13:24<40:35,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 24%|███████████████████▏                                                           | 308/1267 [13:27<40:25,  2.53s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 24%|███████████████████▎                                                           | 309/1267 [13:29<40:46,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 24%|███████████████████▎                                                           | 310/1267 [13:32<41:12,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 25%|███████████████████▍                                                           | 311/1267 [13:35<41:21,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 25%|███████████████████▍                                                           | 312/1267 [13:37<40:50,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 25%|███████████████████▌                                                           | 313/1267 [13:40<40:43,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 25%|███████████████████▌                                                           | 314/1267 [13:42<40:32,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 25%|███████████████████▋                                                           | 315/1267 [13:45<40:49,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 25%|███████████████████▋                                                           | 316/1267 [13:47<40:37,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 25%|███████████████████▊                                                           | 317/1267 [13:50<40:48,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 25%|███████████████████▊                                                           | 318/1267 [13:53<40:57,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 25%|███████████████████▉                                                           | 319/1267 [13:55<40:44,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 25%|███████████████████▉                                                           | 320/1267 [13:58<40:42,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 25%|████████████████████                                                           | 321/1267 [14:00<40:33,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 25%|████████████████████                                                           | 322/1267 [14:03<40:33,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 25%|████████████████████▏                                                          | 323/1267 [14:05<40:34,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 228886

 26%|████████████████████▏                                                          | 324/1267 [14:08<41:19,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 150590

 26%|████████████████████▎                                                          | 325/1267 [14:11<41:35,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 26%|████████████████████▎                                                          | 326/1267 [14:14<41:55,  2.67s/it]

Created 300 windows of shape (128, 4) from sequence of length 111100

 26%|████████████████████▍                                                          | 327/1267 [14:16<41:40,  2.66s/it]

Created 300 windows of shape (128, 4) from sequence of length 21097

 26%|████████████████████▍                                                          | 328/1267 [14:19<42:16,  2.70s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 26%|████████████████████▌                                                          | 329/1267 [14:22<42:26,  2.71s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 26%|████████████████████▌                                                          | 330/1267 [14:25<42:30,  2.72s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 26%|████████████████████▋                                                          | 331/1267 [14:27<42:29,  2.72s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 26%|████████████████████▋                                                          | 332/1267 [14:30<42:35,  2.73s/it]

Created 300 windows of shape (128, 4) from sequence of length 225461

 26%|████████████████████▊                                                          | 333/1267 [14:33<42:33,  2.73s/it]

Created 300 windows of shape (128, 4) from sequence of length 147848

 26%|████████████████████▊                                                          | 334/1267 [14:35<42:15,  2.72s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 26%|████████████████████▉                                                          | 335/1267 [14:38<41:35,  2.68s/it]

Created 300 windows of shape (128, 4) from sequence of length 102800

 27%|████████████████████▉                                                          | 336/1267 [14:41<41:28,  2.67s/it]

Created 300 windows of shape (128, 4) from sequence of length 27997

 27%|█████████████████████                                                          | 337/1267 [14:43<41:09,  2.66s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 27%|█████████████████████                                                          | 338/1267 [14:46<40:38,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 27%|█████████████████████▏                                                         | 339/1267 [14:48<40:23,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 27%|█████████████████████▏                                                         | 340/1267 [14:51<40:10,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 27%|█████████████████████▎                                                         | 341/1267 [14:54<39:43,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 27%|█████████████████████▎                                                         | 342/1267 [14:56<39:52,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 27%|█████████████████████▍                                                         | 343/1267 [14:59<40:12,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 27%|█████████████████████▍                                                         | 344/1267 [15:01<39:56,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 27%|█████████████████████▌                                                         | 345/1267 [15:04<39:32,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 27%|█████████████████████▌                                                         | 346/1267 [15:07<39:38,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 27%|█████████████████████▋                                                         | 347/1267 [15:09<40:04,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 27%|█████████████████████▋                                                         | 348/1267 [15:12<40:24,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 28%|█████████████████████▊                                                         | 349/1267 [15:15<40:20,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 28%|█████████████████████▊                                                         | 350/1267 [15:17<40:29,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 28%|█████████████████████▉                                                         | 351/1267 [15:20<40:16,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 28%|█████████████████████▉                                                         | 352/1267 [15:22<40:09,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 28%|██████████████████████                                                         | 353/1267 [15:25<40:27,  2.66s/it]

Created 300 windows of shape (128, 4) from sequence of length 222583

 28%|██████████████████████                                                         | 354/1267 [15:28<40:03,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 153377

 28%|██████████████████████▏                                                        | 355/1267 [15:30<40:04,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 28%|██████████████████████▏                                                        | 356/1267 [15:33<40:00,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 109000

 28%|██████████████████████▎                                                        | 357/1267 [15:36<39:45,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 30998

 28%|██████████████████████▎                                                        | 358/1267 [15:38<39:34,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 28%|██████████████████████▍                                                        | 359/1267 [15:41<39:37,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 28%|██████████████████████▍                                                        | 360/1267 [15:43<39:28,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 28%|██████████████████████▌                                                        | 361/1267 [15:46<39:17,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 29%|██████████████████████▌                                                        | 362/1267 [15:49<39:29,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 235419

 29%|██████████████████████▋                                                        | 363/1267 [15:51<39:05,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 149607

 29%|██████████████████████▋                                                        | 364/1267 [15:54<38:45,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 29%|██████████████████████▊                                                        | 365/1267 [15:56<38:27,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 100600

 29%|██████████████████████▊                                                        | 366/1267 [15:59<38:16,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 32098

 29%|██████████████████████▉                                                        | 367/1267 [16:01<38:35,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 29%|██████████████████████▉                                                        | 368/1267 [16:04<38:42,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 29%|███████████████████████                                                        | 369/1267 [16:07<39:09,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 29%|███████████████████████                                                        | 370/1267 [16:09<39:30,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 29%|███████████████████████▏                                                       | 371/1267 [16:12<39:25,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 230313

 29%|███████████████████████▏                                                       | 372/1267 [16:15<39:25,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 150182

 29%|███████████████████████▎                                                       | 373/1267 [16:17<39:12,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 30592

 30%|███████████████████████▎                                                       | 374/1267 [16:20<39:12,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 96100

 30%|███████████████████████▍                                                       | 375/1267 [16:23<39:04,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 32898

 30%|███████████████████████▍                                                       | 376/1267 [16:25<38:37,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 30%|███████████████████████▌                                                       | 377/1267 [16:28<38:42,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 30%|███████████████████████▌                                                       | 378/1267 [16:30<38:21,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 30%|███████████████████████▋                                                       | 379/1267 [16:33<38:47,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 30%|███████████████████████▋                                                       | 380/1267 [16:36<39:05,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 30%|███████████████████████▊                                                       | 381/1267 [16:38<38:45,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 30%|███████████████████████▊                                                       | 382/1267 [16:41<38:54,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 30%|███████████████████████▉                                                       | 383/1267 [16:44<38:59,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 30%|███████████████████████▉                                                       | 384/1267 [16:46<39:18,  2.67s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 30%|████████████████████████                                                       | 385/1267 [16:49<39:03,  2.66s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 30%|████████████████████████                                                       | 386/1267 [16:52<38:50,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 31%|████████████████████████▏                                                      | 387/1267 [16:54<38:58,  2.66s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 31%|████████████████████████▏                                                      | 388/1267 [16:57<38:37,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 31%|████████████████████████▎                                                      | 389/1267 [16:59<38:31,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 31%|████████████████████████▎                                                      | 390/1267 [17:02<38:29,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 31%|████████████████████████▍                                                      | 391/1267 [17:05<38:23,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 31%|████████████████████████▍                                                      | 392/1267 [17:07<38:07,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 226896

 31%|████████████████████████▌                                                      | 393/1267 [17:10<38:10,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 147189

 31%|████████████████████████▌                                                      | 394/1267 [17:13<38:12,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 30592

 31%|████████████████████████▋                                                      | 395/1267 [17:15<38:05,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 110400

 31%|████████████████████████▋                                                      | 396/1267 [17:18<38:05,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 21997

 31%|████████████████████████▊                                                      | 397/1267 [17:20<38:07,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 31%|████████████████████████▊                                                      | 398/1267 [17:23<38:03,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 31%|████████████████████████▉                                                      | 399/1267 [17:26<38:08,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 32%|████████████████████████▉                                                      | 400/1267 [17:28<38:10,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 32%|█████████████████████████                                                      | 401/1267 [17:31<38:10,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 229185

 32%|█████████████████████████                                                      | 402/1267 [17:34<37:47,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 150429

 32%|█████████████████████████▏                                                     | 403/1267 [17:36<37:19,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 30592

 32%|█████████████████████████▏                                                     | 404/1267 [17:39<36:58,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 107700

 32%|█████████████████████████▎                                                     | 405/1267 [17:41<36:49,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 21497

 32%|█████████████████████████▎                                                     | 406/1267 [17:44<36:49,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 32%|█████████████████████████▍                                                     | 407/1267 [17:46<36:21,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 32%|█████████████████████████▍                                                     | 408/1267 [17:49<36:30,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 32%|█████████████████████████▌                                                     | 409/1267 [17:51<36:27,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 32%|█████████████████████████▌                                                     | 410/1267 [17:54<36:13,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 228869

 32%|█████████████████████████▋                                                     | 411/1267 [17:56<36:20,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 151281

 33%|█████████████████████████▋                                                     | 412/1267 [17:59<36:36,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 33%|█████████████████████████▊                                                     | 413/1267 [18:02<36:29,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 106600

 33%|█████████████████████████▊                                                     | 414/1267 [18:04<36:20,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 25298

 33%|█████████████████████████▉                                                     | 415/1267 [18:07<36:19,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 33%|█████████████████████████▉                                                     | 416/1267 [18:09<35:59,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 33%|██████████████████████████                                                     | 417/1267 [18:12<36:02,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 33%|██████████████████████████                                                     | 418/1267 [18:14<35:50,  2.53s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 33%|██████████████████████████▏                                                    | 419/1267 [18:17<35:46,  2.53s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 33%|██████████████████████████▏                                                    | 420/1267 [18:19<35:48,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 33%|██████████████████████████▎                                                    | 421/1267 [18:22<35:35,  2.52s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 33%|██████████████████████████▎                                                    | 422/1267 [18:24<35:24,  2.51s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 33%|██████████████████████████▎                                                    | 423/1267 [18:27<35:26,  2.52s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 33%|██████████████████████████▍                                                    | 424/1267 [18:29<35:16,  2.51s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 34%|██████████████████████████▍                                                    | 425/1267 [18:32<35:28,  2.53s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 34%|██████████████████████████▌                                                    | 426/1267 [18:34<35:34,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 34%|██████████████████████████▌                                                    | 427/1267 [18:37<35:28,  2.53s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 34%|██████████████████████████▋                                                    | 428/1267 [18:40<35:32,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 34%|██████████████████████████▋                                                    | 429/1267 [18:42<35:36,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 34%|██████████████████████████▊                                                    | 430/1267 [18:45<35:48,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 34%|██████████████████████████▊                                                    | 431/1267 [18:47<35:39,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 34%|██████████████████████████▉                                                    | 432/1267 [18:50<35:59,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 34%|██████████████████████████▉                                                    | 433/1267 [18:52<35:50,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 34%|███████████████████████████                                                    | 434/1267 [18:55<35:49,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 34%|███████████████████████████                                                    | 435/1267 [18:58<35:43,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 228886

 34%|███████████████████████████▏                                                   | 436/1267 [19:00<35:53,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 150590

 34%|███████████████████████████▏                                                   | 437/1267 [19:03<35:49,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 35%|███████████████████████████▎                                                   | 438/1267 [19:05<35:25,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 111100

 35%|███████████████████████████▎                                                   | 439/1267 [19:08<35:37,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 21097

 35%|███████████████████████████▍                                                   | 440/1267 [19:11<35:56,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 35%|███████████████████████████▍                                                   | 441/1267 [19:13<35:58,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 35%|███████████████████████████▌                                                   | 442/1267 [19:16<35:56,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 35%|███████████████████████████▌                                                   | 443/1267 [19:18<35:47,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 35%|███████████████████████████▋                                                   | 444/1267 [19:21<35:45,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 225461

 35%|███████████████████████████▋                                                   | 445/1267 [19:24<35:55,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 147848

 35%|███████████████████████████▊                                                   | 446/1267 [19:26<35:45,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 35%|███████████████████████████▊                                                   | 447/1267 [19:29<35:45,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 102800

 35%|███████████████████████████▉                                                   | 448/1267 [19:32<35:48,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 27997

 35%|███████████████████████████▉                                                   | 449/1267 [19:34<35:45,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 36%|████████████████████████████                                                   | 450/1267 [19:37<35:29,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 36%|████████████████████████████                                                   | 451/1267 [19:39<35:21,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 36%|████████████████████████████▏                                                  | 452/1267 [19:42<35:03,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 36%|████████████████████████████▏                                                  | 453/1267 [19:44<34:54,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 36%|████████████████████████████▎                                                  | 454/1267 [19:47<35:12,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 36%|████████████████████████████▎                                                  | 455/1267 [19:50<35:02,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 36%|████████████████████████████▍                                                  | 456/1267 [19:52<35:24,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 36%|████████████████████████████▍                                                  | 457/1267 [19:55<34:57,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 36%|████████████████████████████▌                                                  | 458/1267 [19:57<34:46,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 36%|████████████████████████████▌                                                  | 459/1267 [20:00<34:35,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 36%|████████████████████████████▋                                                  | 460/1267 [20:03<34:31,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 36%|████████████████████████████▋                                                  | 461/1267 [20:05<34:48,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 36%|████████████████████████████▊                                                  | 462/1267 [20:08<35:11,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 37%|████████████████████████████▊                                                  | 463/1267 [20:10<34:57,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 37%|████████████████████████████▉                                                  | 464/1267 [20:13<34:52,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 37%|████████████████████████████▉                                                  | 465/1267 [20:16<35:41,  2.67s/it]

Created 300 windows of shape (128, 4) from sequence of length 222583

 37%|█████████████████████████████                                                  | 466/1267 [20:19<35:28,  2.66s/it]

Created 300 windows of shape (128, 4) from sequence of length 153377

 37%|█████████████████████████████                                                  | 467/1267 [20:21<35:27,  2.66s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 37%|█████████████████████████████▏                                                 | 468/1267 [20:24<35:37,  2.68s/it]

Created 300 windows of shape (128, 4) from sequence of length 109000

 37%|█████████████████████████████▏                                                 | 469/1267 [20:27<35:35,  2.68s/it]

Created 300 windows of shape (128, 4) from sequence of length 30998

 37%|█████████████████████████████▎                                                 | 470/1267 [20:29<35:43,  2.69s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 37%|█████████████████████████████▎                                                 | 471/1267 [20:32<35:47,  2.70s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 37%|█████████████████████████████▍                                                 | 472/1267 [20:35<35:56,  2.71s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 37%|█████████████████████████████▍                                                 | 473/1267 [20:37<35:35,  2.69s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 37%|█████████████████████████████▌                                                 | 474/1267 [20:40<35:22,  2.68s/it]

Created 300 windows of shape (128, 4) from sequence of length 235419

 37%|█████████████████████████████▌                                                 | 475/1267 [20:43<35:06,  2.66s/it]

Created 300 windows of shape (128, 4) from sequence of length 149607

 38%|█████████████████████████████▋                                                 | 476/1267 [20:45<34:57,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 38%|█████████████████████████████▋                                                 | 477/1267 [20:48<34:29,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 100600

 38%|█████████████████████████████▊                                                 | 478/1267 [20:50<34:16,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 32098

 38%|█████████████████████████████▊                                                 | 479/1267 [20:53<34:10,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 38%|█████████████████████████████▉                                                 | 480/1267 [20:56<34:03,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 38%|█████████████████████████████▉                                                 | 481/1267 [20:58<33:54,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 38%|██████████████████████████████                                                 | 482/1267 [21:01<34:10,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 38%|██████████████████████████████                                                 | 483/1267 [21:03<34:24,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 230313

 38%|██████████████████████████████▏                                                | 484/1267 [21:06<34:01,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 150182

 38%|██████████████████████████████▏                                                | 485/1267 [21:09<34:00,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 30592

 38%|██████████████████████████████▎                                                | 486/1267 [21:11<33:58,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 96100

 38%|██████████████████████████████▎                                                | 487/1267 [21:14<33:51,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 32898

 39%|██████████████████████████████▍                                                | 488/1267 [21:16<33:48,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 39%|██████████████████████████████▍                                                | 489/1267 [21:19<33:48,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 39%|██████████████████████████████▌                                                | 490/1267 [21:22<33:58,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 39%|██████████████████████████████▌                                                | 491/1267 [21:24<33:53,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 39%|██████████████████████████████▋                                                | 492/1267 [21:27<33:48,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 39%|██████████████████████████████▋                                                | 493/1267 [21:30<34:05,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 39%|██████████████████████████████▊                                                | 494/1267 [21:32<33:50,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 39%|██████████████████████████████▊                                                | 495/1267 [21:35<33:42,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 39%|██████████████████████████████▉                                                | 496/1267 [21:37<33:41,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 39%|██████████████████████████████▉                                                | 497/1267 [21:40<33:19,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 39%|███████████████████████████████                                                | 498/1267 [21:43<33:31,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 39%|███████████████████████████████                                                | 499/1267 [21:45<33:19,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 39%|███████████████████████████████▏                                               | 500/1267 [21:48<33:29,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 40%|███████████████████████████████▏                                               | 501/1267 [21:51<33:27,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 40%|███████████████████████████████▎                                               | 502/1267 [21:53<33:21,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 40%|███████████████████████████████▎                                               | 503/1267 [21:56<33:20,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 40%|███████████████████████████████▍                                               | 504/1267 [21:58<33:10,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 226896

 40%|███████████████████████████████▍                                               | 505/1267 [22:01<32:44,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 147189

 40%|███████████████████████████████▌                                               | 506/1267 [22:03<32:36,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 30592

 40%|███████████████████████████████▌                                               | 507/1267 [22:06<32:40,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 110400

 40%|███████████████████████████████▋                                               | 508/1267 [22:09<32:31,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 21997

 40%|███████████████████████████████▋                                               | 509/1267 [22:11<32:43,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 40%|███████████████████████████████▊                                               | 510/1267 [22:14<32:43,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 40%|███████████████████████████████▊                                               | 511/1267 [22:16<32:40,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 40%|███████████████████████████████▉                                               | 512/1267 [22:19<32:32,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 40%|███████████████████████████████▉                                               | 513/1267 [22:22<32:33,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 229185

 41%|████████████████████████████████                                               | 514/1267 [22:24<32:25,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 150429

 41%|████████████████████████████████                                               | 515/1267 [22:27<32:07,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 30592

 41%|████████████████████████████████▏                                              | 516/1267 [22:29<32:23,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 107700

 41%|████████████████████████████████▏                                              | 517/1267 [22:32<32:22,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 21497

 41%|████████████████████████████████▎                                              | 518/1267 [22:35<32:31,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 41%|████████████████████████████████▎                                              | 519/1267 [22:37<32:20,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 41%|████████████████████████████████▍                                              | 520/1267 [22:40<32:13,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 41%|████████████████████████████████▍                                              | 521/1267 [22:42<31:57,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 41%|████████████████████████████████▌                                              | 522/1267 [22:45<31:43,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 228869

 41%|████████████████████████████████▌                                              | 523/1267 [22:47<31:39,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 151281

 41%|████████████████████████████████▋                                              | 524/1267 [22:50<31:26,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 41%|████████████████████████████████▋                                              | 525/1267 [22:52<31:04,  2.51s/it]

Created 300 windows of shape (128, 4) from sequence of length 106600

 42%|████████████████████████████████▊                                              | 526/1267 [22:55<31:15,  2.53s/it]

Created 300 windows of shape (128, 4) from sequence of length 25298

 42%|████████████████████████████████▊                                              | 527/1267 [22:57<31:17,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 42%|████████████████████████████████▉                                              | 528/1267 [23:00<31:10,  2.53s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 42%|████████████████████████████████▉                                              | 529/1267 [23:02<31:15,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 42%|█████████████████████████████████                                              | 530/1267 [23:05<31:14,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 42%|█████████████████████████████████                                              | 531/1267 [23:08<31:09,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 42%|█████████████████████████████████▏                                             | 532/1267 [23:10<30:56,  2.53s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 42%|█████████████████████████████████▏                                             | 533/1267 [23:12<30:44,  2.51s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 42%|█████████████████████████████████▎                                             | 534/1267 [23:15<30:53,  2.53s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 42%|█████████████████████████████████▎                                             | 535/1267 [23:18<31:06,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 42%|█████████████████████████████████▍                                             | 536/1267 [23:20<31:00,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 42%|█████████████████████████████████▍                                             | 537/1267 [23:23<30:54,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 42%|█████████████████████████████████▌                                             | 538/1267 [23:25<30:52,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 43%|█████████████████████████████████▌                                             | 539/1267 [23:28<30:49,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 43%|█████████████████████████████████▋                                             | 540/1267 [23:30<31:01,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 43%|█████████████████████████████████▋                                             | 541/1267 [23:33<31:36,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 43%|█████████████████████████████████▊                                             | 542/1267 [23:36<31:25,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 43%|█████████████████████████████████▊                                             | 543/1267 [23:38<30:59,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 43%|█████████████████████████████████▉                                             | 544/1267 [23:41<30:49,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 43%|█████████████████████████████████▉                                             | 545/1267 [23:43<30:34,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 43%|██████████████████████████████████                                             | 546/1267 [23:46<30:33,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 43%|██████████████████████████████████                                             | 547/1267 [23:48<30:28,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 228886

 43%|██████████████████████████████████▏                                            | 548/1267 [23:51<30:39,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 150590

 43%|██████████████████████████████████▏                                            | 549/1267 [23:53<30:30,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 43%|██████████████████████████████████▎                                            | 550/1267 [23:56<30:22,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 111100

 43%|██████████████████████████████████▎                                            | 551/1267 [23:59<30:33,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 21097

 44%|██████████████████████████████████▍                                            | 552/1267 [24:01<30:29,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 44%|██████████████████████████████████▍                                            | 553/1267 [24:04<30:31,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 44%|██████████████████████████████████▌                                            | 554/1267 [24:06<30:48,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 44%|██████████████████████████████████▌                                            | 555/1267 [24:09<30:52,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 44%|██████████████████████████████████▋                                            | 556/1267 [24:12<31:02,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 225461

 44%|██████████████████████████████████▋                                            | 557/1267 [24:14<30:58,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 147848

 44%|██████████████████████████████████▊                                            | 558/1267 [24:17<31:12,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 44%|██████████████████████████████████▊                                            | 559/1267 [24:20<30:51,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 102800

 44%|██████████████████████████████████▉                                            | 560/1267 [24:22<31:15,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 27997

 44%|██████████████████████████████████▉                                            | 561/1267 [24:25<30:48,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 44%|███████████████████████████████████                                            | 562/1267 [24:28<31:03,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 44%|███████████████████████████████████                                            | 563/1267 [24:30<30:58,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 45%|███████████████████████████████████▏                                           | 564/1267 [24:33<30:57,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 45%|███████████████████████████████████▏                                           | 565/1267 [24:35<30:54,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 45%|███████████████████████████████████▎                                           | 566/1267 [24:38<30:36,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 45%|███████████████████████████████████▎                                           | 567/1267 [24:41<30:28,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 45%|███████████████████████████████████▍                                           | 568/1267 [24:43<30:29,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 45%|███████████████████████████████████▍                                           | 569/1267 [24:46<30:27,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 45%|███████████████████████████████████▌                                           | 570/1267 [24:48<30:30,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 45%|███████████████████████████████████▌                                           | 571/1267 [24:51<30:18,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 45%|███████████████████████████████████▋                                           | 572/1267 [24:54<30:22,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 45%|███████████████████████████████████▋                                           | 573/1267 [24:56<30:17,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 45%|███████████████████████████████████▊                                           | 574/1267 [24:59<30:24,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 45%|███████████████████████████████████▊                                           | 575/1267 [25:02<30:23,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 45%|███████████████████████████████████▉                                           | 576/1267 [25:04<30:37,  2.66s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 46%|███████████████████████████████████▉                                           | 577/1267 [25:07<30:39,  2.67s/it]

Created 300 windows of shape (128, 4) from sequence of length 222583

 46%|████████████████████████████████████                                           | 578/1267 [25:10<30:20,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 153377

 46%|████████████████████████████████████                                           | 579/1267 [25:12<30:11,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 46%|████████████████████████████████████▏                                          | 580/1267 [25:15<30:09,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 109000

 46%|████████████████████████████████████▏                                          | 581/1267 [25:17<30:00,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 30998

 46%|████████████████████████████████████▎                                          | 582/1267 [25:20<30:06,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 46%|████████████████████████████████████▎                                          | 583/1267 [25:23<30:15,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 46%|████████████████████████████████████▍                                          | 584/1267 [25:26<30:21,  2.67s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 46%|████████████████████████████████████▍                                          | 585/1267 [25:28<30:17,  2.67s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 46%|████████████████████████████████████▌                                          | 586/1267 [25:31<30:28,  2.69s/it]

Created 300 windows of shape (128, 4) from sequence of length 235419

 46%|████████████████████████████████████▌                                          | 587/1267 [25:34<30:13,  2.67s/it]

Created 300 windows of shape (128, 4) from sequence of length 149607

 46%|████████████████████████████████████▋                                          | 588/1267 [25:36<30:12,  2.67s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 46%|████████████████████████████████████▋                                          | 589/1267 [25:39<29:59,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 100600

 47%|████████████████████████████████████▊                                          | 590/1267 [25:41<29:33,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 32098

 47%|████████████████████████████████████▊                                          | 591/1267 [25:44<29:34,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 47%|████████████████████████████████████▉                                          | 592/1267 [25:47<29:40,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 47%|████████████████████████████████████▉                                          | 593/1267 [25:49<29:34,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 47%|█████████████████████████████████████                                          | 594/1267 [25:52<29:20,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 47%|█████████████████████████████████████                                          | 595/1267 [25:54<29:07,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 230313

 47%|█████████████████████████████████████▏                                         | 596/1267 [25:57<29:00,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 150182

 47%|█████████████████████████████████████▏                                         | 597/1267 [26:00<28:49,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 30592

 47%|█████████████████████████████████████▎                                         | 598/1267 [26:02<28:37,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 96100

 47%|█████████████████████████████████████▎                                         | 599/1267 [26:05<28:27,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 32898

 47%|█████████████████████████████████████▍                                         | 600/1267 [26:07<28:25,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 47%|█████████████████████████████████████▍                                         | 601/1267 [26:10<28:34,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 48%|█████████████████████████████████████▌                                         | 602/1267 [26:12<28:42,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 48%|█████████████████████████████████████▌                                         | 603/1267 [26:15<28:36,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 48%|█████████████████████████████████████▋                                         | 604/1267 [26:18<28:41,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 48%|█████████████████████████████████████▋                                         | 605/1267 [26:20<28:32,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 48%|█████████████████████████████████████▊                                         | 606/1267 [26:23<28:33,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 48%|█████████████████████████████████████▊                                         | 607/1267 [26:25<28:38,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 48%|█████████████████████████████████████▉                                         | 608/1267 [26:28<28:22,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 48%|█████████████████████████████████████▉                                         | 609/1267 [26:31<28:21,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 48%|██████████████████████████████████████                                         | 610/1267 [26:33<28:25,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 48%|██████████████████████████████████████                                         | 611/1267 [26:36<28:20,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 48%|██████████████████████████████████████▏                                        | 612/1267 [26:38<28:25,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 48%|██████████████████████████████████████▏                                        | 613/1267 [26:41<28:27,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 48%|██████████████████████████████████████▎                                        | 614/1267 [26:44<28:39,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 49%|██████████████████████████████████████▎                                        | 615/1267 [26:46<28:27,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 49%|██████████████████████████████████████▍                                        | 616/1267 [26:49<28:38,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 226896

 49%|██████████████████████████████████████▍                                        | 617/1267 [26:52<28:14,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 147189

 49%|██████████████████████████████████████▌                                        | 618/1267 [26:54<28:01,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 30592

 49%|██████████████████████████████████████▌                                        | 619/1267 [26:57<27:54,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 110400

 49%|██████████████████████████████████████▋                                        | 620/1267 [26:59<27:48,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 21997

 49%|██████████████████████████████████████▋                                        | 621/1267 [27:02<27:50,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 49%|██████████████████████████████████████▊                                        | 622/1267 [27:04<27:52,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 49%|██████████████████████████████████████▊                                        | 623/1267 [27:07<28:07,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 49%|██████████████████████████████████████▉                                        | 624/1267 [27:10<28:25,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 49%|██████████████████████████████████████▉                                        | 625/1267 [27:12<28:18,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 229185

 49%|███████████████████████████████████████                                        | 626/1267 [27:15<28:27,  2.66s/it]

Created 300 windows of shape (128, 4) from sequence of length 150429

 49%|███████████████████████████████████████                                        | 627/1267 [27:18<28:24,  2.66s/it]

Created 300 windows of shape (128, 4) from sequence of length 30592

 50%|███████████████████████████████████████▏                                       | 628/1267 [27:20<28:03,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 107700

 50%|███████████████████████████████████████▏                                       | 629/1267 [27:23<28:07,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 21497

 50%|███████████████████████████████████████▎                                       | 630/1267 [27:26<27:54,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 50%|███████████████████████████████████████▎                                       | 631/1267 [27:28<27:43,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 50%|███████████████████████████████████████▍                                       | 632/1267 [27:31<27:35,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 50%|███████████████████████████████████████▍                                       | 633/1267 [27:33<27:44,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 50%|███████████████████████████████████████▌                                       | 634/1267 [27:36<27:29,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 228869

 50%|███████████████████████████████████████▌                                       | 635/1267 [27:39<27:26,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 151281

 50%|███████████████████████████████████████▋                                       | 636/1267 [27:41<27:17,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 50%|███████████████████████████████████████▋                                       | 637/1267 [27:44<27:07,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 106600

 50%|███████████████████████████████████████▊                                       | 638/1267 [27:46<27:02,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 25298

 50%|███████████████████████████████████████▊                                       | 639/1267 [27:49<27:05,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 51%|███████████████████████████████████████▉                                       | 640/1267 [27:51<26:50,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 51%|███████████████████████████████████████▉                                       | 641/1267 [27:54<26:35,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 51%|████████████████████████████████████████                                       | 642/1267 [27:56<26:25,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 51%|████████████████████████████████████████                                       | 643/1267 [27:59<26:41,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 51%|████████████████████████████████████████▏                                      | 644/1267 [28:02<26:34,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 51%|████████████████████████████████████████▏                                      | 645/1267 [28:04<26:39,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 51%|████████████████████████████████████████▎                                      | 646/1267 [28:07<26:44,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 51%|████████████████████████████████████████▎                                      | 647/1267 [28:09<26:47,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 51%|████████████████████████████████████████▍                                      | 648/1267 [28:12<26:55,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 51%|████████████████████████████████████████▍                                      | 649/1267 [28:15<26:58,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 51%|████████████████████████████████████████▌                                      | 650/1267 [28:17<26:47,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 51%|████████████████████████████████████████▌                                      | 651/1267 [28:20<26:45,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 51%|████████████████████████████████████████▋                                      | 652/1267 [28:23<26:34,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 52%|████████████████████████████████████████▋                                      | 653/1267 [28:25<26:39,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 52%|████████████████████████████████████████▊                                      | 654/1267 [28:28<26:38,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 52%|████████████████████████████████████████▊                                      | 655/1267 [28:30<26:35,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 52%|████████████████████████████████████████▉                                      | 656/1267 [28:33<26:42,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 52%|████████████████████████████████████████▉                                      | 657/1267 [28:36<26:35,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 52%|█████████████████████████████████████████                                      | 658/1267 [28:38<26:13,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 52%|█████████████████████████████████████████                                      | 659/1267 [28:41<26:16,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 228886

 52%|█████████████████████████████████████████▏                                     | 660/1267 [28:43<26:21,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 150590

 52%|█████████████████████████████████████████▏                                     | 661/1267 [28:46<26:05,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 52%|█████████████████████████████████████████▎                                     | 662/1267 [28:48<25:50,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 111100

 52%|█████████████████████████████████████████▎                                     | 663/1267 [28:51<25:54,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 21097

 52%|█████████████████████████████████████████▍                                     | 664/1267 [28:54<25:44,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 52%|█████████████████████████████████████████▍                                     | 665/1267 [28:56<25:47,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 53%|█████████████████████████████████████████▌                                     | 666/1267 [28:59<25:54,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 53%|█████████████████████████████████████████▌                                     | 667/1267 [29:01<26:00,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 53%|█████████████████████████████████████████▋                                     | 668/1267 [29:04<26:00,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 225461

 53%|█████████████████████████████████████████▋                                     | 669/1267 [29:07<26:11,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 147848

 53%|█████████████████████████████████████████▊                                     | 670/1267 [29:09<26:14,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 53%|█████████████████████████████████████████▊                                     | 671/1267 [29:12<25:56,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 102800

 53%|█████████████████████████████████████████▉                                     | 672/1267 [29:15<25:52,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 27997

 53%|█████████████████████████████████████████▉                                     | 673/1267 [29:17<25:41,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 53%|██████████████████████████████████████████                                     | 674/1267 [29:20<25:40,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 53%|██████████████████████████████████████████                                     | 675/1267 [29:22<25:39,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 53%|██████████████████████████████████████████▏                                    | 676/1267 [29:25<25:38,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 53%|██████████████████████████████████████████▏                                    | 677/1267 [29:28<25:46,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 54%|██████████████████████████████████████████▎                                    | 678/1267 [29:30<25:31,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 54%|██████████████████████████████████████████▎                                    | 679/1267 [29:33<25:46,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 54%|██████████████████████████████████████████▍                                    | 680/1267 [29:35<25:49,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 54%|██████████████████████████████████████████▍                                    | 681/1267 [29:38<25:38,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 54%|██████████████████████████████████████████▌                                    | 682/1267 [29:41<25:32,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 54%|██████████████████████████████████████████▌                                    | 683/1267 [29:43<25:22,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 54%|██████████████████████████████████████████▋                                    | 684/1267 [29:46<25:18,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 54%|██████████████████████████████████████████▋                                    | 685/1267 [29:49<25:36,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 54%|██████████████████████████████████████████▊                                    | 686/1267 [29:51<25:35,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 54%|██████████████████████████████████████████▊                                    | 687/1267 [29:54<25:16,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 54%|██████████████████████████████████████████▉                                    | 688/1267 [29:56<25:07,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 54%|██████████████████████████████████████████▉                                    | 689/1267 [29:59<25:02,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 222583

 54%|███████████████████████████████████████████                                    | 690/1267 [30:02<24:51,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 153377

 55%|███████████████████████████████████████████                                    | 691/1267 [30:04<24:46,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 55%|███████████████████████████████████████████▏                                   | 692/1267 [30:07<24:52,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 109000

 55%|███████████████████████████████████████████▏                                   | 693/1267 [30:09<25:11,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 30998

 55%|███████████████████████████████████████████▎                                   | 694/1267 [30:12<25:13,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 55%|███████████████████████████████████████████▎                                   | 695/1267 [30:15<25:19,  2.66s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 55%|███████████████████████████████████████████▍                                   | 696/1267 [30:17<25:16,  2.66s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 55%|███████████████████████████████████████████▍                                   | 697/1267 [30:20<25:12,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 55%|███████████████████████████████████████████▌                                   | 698/1267 [30:23<25:07,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 235419

 55%|███████████████████████████████████████████▌                                   | 699/1267 [30:25<24:58,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 149607

 55%|███████████████████████████████████████████▋                                   | 700/1267 [30:28<25:01,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 55%|███████████████████████████████████████████▋                                   | 701/1267 [30:31<24:52,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 100600

 55%|███████████████████████████████████████████▊                                   | 702/1267 [30:33<24:43,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 32098

 55%|███████████████████████████████████████████▊                                   | 703/1267 [30:36<24:27,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 56%|███████████████████████████████████████████▉                                   | 704/1267 [30:38<24:09,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 56%|███████████████████████████████████████████▉                                   | 705/1267 [30:41<24:05,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 56%|████████████████████████████████████████████                                   | 706/1267 [30:43<24:06,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 56%|████████████████████████████████████████████                                   | 707/1267 [30:46<24:04,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 230313

 56%|████████████████████████████████████████████▏                                  | 708/1267 [30:49<23:47,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 150182

 56%|████████████████████████████████████████████▏                                  | 709/1267 [30:51<23:35,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 30592

 56%|████████████████████████████████████████████▎                                  | 710/1267 [30:53<23:25,  2.52s/it]

Created 300 windows of shape (128, 4) from sequence of length 96100

 56%|████████████████████████████████████████████▎                                  | 711/1267 [30:56<23:27,  2.53s/it]

Created 300 windows of shape (128, 4) from sequence of length 32898

 56%|████████████████████████████████████████████▍                                  | 712/1267 [30:59<23:27,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 56%|████████████████████████████████████████████▍                                  | 713/1267 [31:01<23:26,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 56%|████████████████████████████████████████████▌                                  | 714/1267 [31:04<23:30,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 56%|████████████████████████████████████████████▌                                  | 715/1267 [31:06<23:26,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 57%|████████████████████████████████████████████▋                                  | 716/1267 [31:09<23:44,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 57%|████████████████████████████████████████████▋                                  | 717/1267 [31:12<23:49,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 57%|████████████████████████████████████████████▊                                  | 718/1267 [31:14<23:51,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 57%|████████████████████████████████████████████▊                                  | 719/1267 [31:17<23:57,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 57%|████████████████████████████████████████████▉                                  | 720/1267 [31:19<23:57,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 57%|████████████████████████████████████████████▉                                  | 721/1267 [31:22<23:48,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 57%|█████████████████████████████████████████████                                  | 722/1267 [31:25<23:51,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 57%|█████████████████████████████████████████████                                  | 723/1267 [31:27<23:49,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 57%|█████████████████████████████████████████████▏                                 | 724/1267 [31:30<23:48,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 57%|█████████████████████████████████████████████▏                                 | 725/1267 [31:33<23:50,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 57%|█████████████████████████████████████████████▎                                 | 726/1267 [31:35<23:51,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 57%|█████████████████████████████████████████████▎                                 | 727/1267 [31:38<23:37,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 57%|█████████████████████████████████████████████▍                                 | 728/1267 [31:40<23:32,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 226896

 58%|█████████████████████████████████████████████▍                                 | 729/1267 [31:43<23:12,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 147189

 58%|█████████████████████████████████████████████▌                                 | 730/1267 [31:46<23:07,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 30592

 58%|█████████████████████████████████████████████▌                                 | 731/1267 [31:48<23:03,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 110400

 58%|█████████████████████████████████████████████▋                                 | 732/1267 [31:51<22:53,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 21997

 58%|█████████████████████████████████████████████▋                                 | 733/1267 [31:53<23:02,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 58%|█████████████████████████████████████████████▊                                 | 734/1267 [31:56<23:06,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 58%|█████████████████████████████████████████████▊                                 | 735/1267 [31:59<23:05,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 58%|█████████████████████████████████████████████▉                                 | 736/1267 [32:01<22:59,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 58%|█████████████████████████████████████████████▉                                 | 737/1267 [32:04<22:53,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 229185

 58%|██████████████████████████████████████████████                                 | 738/1267 [32:06<22:58,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 150429

 58%|██████████████████████████████████████████████                                 | 739/1267 [32:09<23:05,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 30592

 58%|██████████████████████████████████████████████▏                                | 740/1267 [32:12<23:06,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 107700

 58%|██████████████████████████████████████████████▏                                | 741/1267 [32:14<22:58,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 21497

 59%|██████████████████████████████████████████████▎                                | 742/1267 [32:17<23:03,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 59%|██████████████████████████████████████████████▎                                | 743/1267 [32:20<22:55,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 59%|██████████████████████████████████████████████▍                                | 744/1267 [32:22<22:47,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 59%|██████████████████████████████████████████████▍                                | 745/1267 [32:25<22:47,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 59%|██████████████████████████████████████████████▌                                | 746/1267 [32:27<22:45,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 228869

 59%|██████████████████████████████████████████████▌                                | 747/1267 [32:30<22:44,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 151281

 59%|██████████████████████████████████████████████▋                                | 748/1267 [32:33<22:39,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 59%|██████████████████████████████████████████████▋                                | 749/1267 [32:35<22:34,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 106600

 59%|██████████████████████████████████████████████▊                                | 750/1267 [32:38<22:34,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 25298

 59%|██████████████████████████████████████████████▊                                | 751/1267 [32:40<22:25,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 59%|██████████████████████████████████████████████▉                                | 752/1267 [32:43<22:28,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 59%|██████████████████████████████████████████████▉                                | 753/1267 [32:46<22:11,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 60%|███████████████████████████████████████████████                                | 754/1267 [32:48<22:01,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 60%|███████████████████████████████████████████████                                | 755/1267 [32:51<21:58,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 60%|███████████████████████████████████████████████▏                               | 756/1267 [32:53<21:58,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 60%|███████████████████████████████████████████████▏                               | 757/1267 [32:56<22:01,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 60%|███████████████████████████████████████████████▎                               | 758/1267 [32:59<21:58,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 60%|███████████████████████████████████████████████▎                               | 759/1267 [33:01<21:57,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 60%|███████████████████████████████████████████████▍                               | 760/1267 [33:04<21:49,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 60%|███████████████████████████████████████████████▍                               | 761/1267 [33:06<21:53,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 60%|███████████████████████████████████████████████▌                               | 762/1267 [33:09<22:03,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 60%|███████████████████████████████████████████████▌                               | 763/1267 [33:12<21:57,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 60%|███████████████████████████████████████████████▋                               | 764/1267 [33:14<21:53,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 60%|███████████████████████████████████████████████▋                               | 765/1267 [33:17<22:10,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 60%|███████████████████████████████████████████████▊                               | 766/1267 [33:20<22:04,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 61%|███████████████████████████████████████████████▊                               | 767/1267 [33:22<22:07,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 61%|███████████████████████████████████████████████▉                               | 768/1267 [33:25<22:09,  2.67s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 61%|███████████████████████████████████████████████▉                               | 769/1267 [33:28<22:10,  2.67s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 61%|████████████████████████████████████████████████                               | 770/1267 [33:30<21:54,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 61%|████████████████████████████████████████████████                               | 771/1267 [33:33<21:53,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 228886

 61%|████████████████████████████████████████████████▏                              | 772/1267 [33:36<21:57,  2.66s/it]

Created 300 windows of shape (128, 4) from sequence of length 150590

 61%|████████████████████████████████████████████████▏                              | 773/1267 [33:38<21:40,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 61%|████████████████████████████████████████████████▎                              | 774/1267 [33:41<21:23,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 111100

 61%|████████████████████████████████████████████████▎                              | 775/1267 [33:43<21:16,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 21097

 61%|████████████████████████████████████████████████▍                              | 776/1267 [33:46<21:03,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 61%|████████████████████████████████████████████████▍                              | 777/1267 [33:48<21:03,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 61%|████████████████████████████████████████████████▌                              | 778/1267 [33:51<21:04,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 61%|████████████████████████████████████████████████▌                              | 779/1267 [33:54<21:04,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 62%|████████████████████████████████████████████████▋                              | 780/1267 [33:56<21:03,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 225461

 62%|████████████████████████████████████████████████▋                              | 781/1267 [33:59<20:57,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 147848

 62%|████████████████████████████████████████████████▊                              | 782/1267 [34:01<20:44,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 62%|████████████████████████████████████████████████▊                              | 783/1267 [34:04<20:45,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 102800

 62%|████████████████████████████████████████████████▉                              | 784/1267 [34:06<20:49,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 27997

 62%|████████████████████████████████████████████████▉                              | 785/1267 [34:09<20:50,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 62%|█████████████████████████████████████████████████                              | 786/1267 [34:12<20:44,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 62%|█████████████████████████████████████████████████                              | 787/1267 [34:14<20:49,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 62%|█████████████████████████████████████████████████▏                             | 788/1267 [34:17<20:55,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 62%|█████████████████████████████████████████████████▏                             | 789/1267 [34:20<20:49,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 62%|█████████████████████████████████████████████████▎                             | 790/1267 [34:22<20:50,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 62%|█████████████████████████████████████████████████▎                             | 791/1267 [34:25<20:56,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 63%|█████████████████████████████████████████████████▍                             | 792/1267 [34:27<20:47,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 63%|█████████████████████████████████████████████████▍                             | 793/1267 [34:30<20:48,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 63%|█████████████████████████████████████████████████▌                             | 794/1267 [34:33<20:37,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 63%|█████████████████████████████████████████████████▌                             | 795/1267 [34:35<20:46,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 63%|█████████████████████████████████████████████████▋                             | 796/1267 [34:38<20:27,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 63%|█████████████████████████████████████████████████▋                             | 797/1267 [34:41<20:27,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 63%|█████████████████████████████████████████████████▊                             | 798/1267 [34:43<20:33,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 63%|█████████████████████████████████████████████████▊                             | 799/1267 [34:46<20:37,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 63%|█████████████████████████████████████████████████▉                             | 800/1267 [34:49<20:31,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 63%|█████████████████████████████████████████████████▉                             | 801/1267 [34:51<20:31,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 222583

 63%|██████████████████████████████████████████████████                             | 802/1267 [34:54<20:32,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 153377

 63%|██████████████████████████████████████████████████                             | 803/1267 [34:56<20:12,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 63%|██████████████████████████████████████████████████▏                            | 804/1267 [34:59<20:00,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 109000

 64%|██████████████████████████████████████████████████▏                            | 805/1267 [35:01<19:54,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 30998

 64%|██████████████████████████████████████████████████▎                            | 806/1267 [35:04<20:00,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 64%|██████████████████████████████████████████████████▎                            | 807/1267 [35:07<20:21,  2.66s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 64%|██████████████████████████████████████████████████▍                            | 808/1267 [35:10<20:28,  2.68s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 64%|██████████████████████████████████████████████████▍                            | 809/1267 [35:12<20:33,  2.69s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 64%|██████████████████████████████████████████████████▌                            | 810/1267 [35:15<20:24,  2.68s/it]

Created 300 windows of shape (128, 4) from sequence of length 235419

 64%|██████████████████████████████████████████████████▌                            | 811/1267 [35:18<20:12,  2.66s/it]

Created 300 windows of shape (128, 4) from sequence of length 149607

 64%|██████████████████████████████████████████████████▋                            | 812/1267 [35:20<20:04,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 64%|██████████████████████████████████████████████████▋                            | 813/1267 [35:23<20:05,  2.66s/it]

Created 300 windows of shape (128, 4) from sequence of length 100600

 64%|██████████████████████████████████████████████████▊                            | 814/1267 [35:26<20:11,  2.67s/it]

Created 300 windows of shape (128, 4) from sequence of length 32098

 64%|██████████████████████████████████████████████████▊                            | 815/1267 [35:28<20:11,  2.68s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 64%|██████████████████████████████████████████████████▉                            | 816/1267 [35:31<20:18,  2.70s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 64%|██████████████████████████████████████████████████▉                            | 817/1267 [35:34<20:20,  2.71s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 65%|███████████████████████████████████████████████████                            | 818/1267 [35:36<20:13,  2.70s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 65%|███████████████████████████████████████████████████                            | 819/1267 [35:39<19:56,  2.67s/it]

Created 300 windows of shape (128, 4) from sequence of length 230313

 65%|███████████████████████████████████████████████████▏                           | 820/1267 [35:42<19:52,  2.67s/it]

Created 300 windows of shape (128, 4) from sequence of length 150182

 65%|███████████████████████████████████████████████████▏                           | 821/1267 [35:44<19:39,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 30592

 65%|███████████████████████████████████████████████████▎                           | 822/1267 [35:47<19:28,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 96100

 65%|███████████████████████████████████████████████████▎                           | 823/1267 [35:49<19:16,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 32898

 65%|███████████████████████████████████████████████████▍                           | 824/1267 [35:52<19:08,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 65%|███████████████████████████████████████████████████▍                           | 825/1267 [35:55<19:02,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 65%|███████████████████████████████████████████████████▌                           | 826/1267 [35:57<18:50,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 65%|███████████████████████████████████████████████████▌                           | 827/1267 [36:00<18:50,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 65%|███████████████████████████████████████████████████▋                           | 828/1267 [36:02<18:45,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 65%|███████████████████████████████████████████████████▋                           | 829/1267 [36:05<18:28,  2.53s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 66%|███████████████████████████████████████████████████▊                           | 830/1267 [36:07<18:43,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 66%|███████████████████████████████████████████████████▊                           | 831/1267 [36:10<18:44,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 66%|███████████████████████████████████████████████████▉                           | 832/1267 [36:13<18:38,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 66%|███████████████████████████████████████████████████▉                           | 833/1267 [36:15<18:44,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 66%|████████████████████████████████████████████████████                           | 834/1267 [36:18<18:37,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 66%|████████████████████████████████████████████████████                           | 835/1267 [36:20<18:44,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 66%|████████████████████████████████████████████████████▏                          | 836/1267 [36:23<18:41,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 66%|████████████████████████████████████████████████████▏                          | 837/1267 [36:26<18:56,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 66%|████████████████████████████████████████████████████▎                          | 838/1267 [36:28<18:54,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 66%|████████████████████████████████████████████████████▎                          | 839/1267 [36:31<18:52,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 66%|████████████████████████████████████████████████████▍                          | 840/1267 [36:34<18:49,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 226896

 66%|████████████████████████████████████████████████████▍                          | 841/1267 [36:36<18:42,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 147189

 66%|████████████████████████████████████████████████████▌                          | 842/1267 [36:39<18:26,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 30592

 67%|████████████████████████████████████████████████████▌                          | 843/1267 [36:41<18:18,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 110400

 67%|████████████████████████████████████████████████████▋                          | 844/1267 [36:44<18:13,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 21997

 67%|████████████████████████████████████████████████████▋                          | 845/1267 [36:47<18:20,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 67%|████████████████████████████████████████████████████▋                          | 846/1267 [36:49<18:19,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 67%|████████████████████████████████████████████████████▊                          | 847/1267 [36:52<18:18,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 67%|████████████████████████████████████████████████████▊                          | 848/1267 [36:54<18:15,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 67%|████████████████████████████████████████████████████▉                          | 849/1267 [36:57<18:13,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 229185

 67%|████████████████████████████████████████████████████▉                          | 850/1267 [37:00<18:03,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 150429

 67%|█████████████████████████████████████████████████████                          | 851/1267 [37:02<18:03,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 30592

 67%|█████████████████████████████████████████████████████                          | 852/1267 [37:05<18:08,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 107700

 67%|█████████████████████████████████████████████████████▏                         | 853/1267 [37:08<18:05,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 21497

 67%|█████████████████████████████████████████████████████▏                         | 854/1267 [37:10<18:08,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 67%|█████████████████████████████████████████████████████▎                         | 855/1267 [37:13<18:01,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 68%|█████████████████████████████████████████████████████▎                         | 856/1267 [37:15<17:59,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 68%|█████████████████████████████████████████████████████▍                         | 857/1267 [37:18<18:01,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 68%|█████████████████████████████████████████████████████▍                         | 858/1267 [37:21<17:59,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 228869

 68%|█████████████████████████████████████████████████████▌                         | 859/1267 [37:23<17:56,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 151281

 68%|█████████████████████████████████████████████████████▌                         | 860/1267 [37:26<17:51,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 68%|█████████████████████████████████████████████████████▋                         | 861/1267 [37:29<17:43,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 106600

 68%|█████████████████████████████████████████████████████▋                         | 862/1267 [37:31<17:40,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 25298

 68%|█████████████████████████████████████████████████████▊                         | 863/1267 [37:34<17:38,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 68%|█████████████████████████████████████████████████████▊                         | 864/1267 [37:36<17:28,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 68%|█████████████████████████████████████████████████████▉                         | 865/1267 [37:39<17:12,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 68%|█████████████████████████████████████████████████████▉                         | 866/1267 [37:41<17:00,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 68%|██████████████████████████████████████████████████████                         | 867/1267 [37:44<16:56,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 69%|██████████████████████████████████████████████████████                         | 868/1267 [37:46<16:47,  2.53s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 69%|██████████████████████████████████████████████████████▏                        | 869/1267 [37:49<16:51,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 69%|██████████████████████████████████████████████████████▏                        | 870/1267 [37:52<16:52,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 69%|██████████████████████████████████████████████████████▎                        | 871/1267 [37:54<16:52,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 69%|██████████████████████████████████████████████████████▎                        | 872/1267 [37:57<16:53,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 69%|██████████████████████████████████████████████████████▍                        | 873/1267 [37:59<16:56,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 69%|██████████████████████████████████████████████████████▍                        | 874/1267 [38:02<16:51,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 69%|██████████████████████████████████████████████████████▌                        | 875/1267 [38:04<16:46,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 69%|██████████████████████████████████████████████████████▌                        | 876/1267 [38:07<16:47,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 69%|██████████████████████████████████████████████████████▋                        | 877/1267 [38:10<16:52,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 69%|██████████████████████████████████████████████████████▋                        | 878/1267 [38:12<16:52,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 69%|██████████████████████████████████████████████████████▊                        | 879/1267 [38:15<16:55,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 69%|██████████████████████████████████████████████████████▊                        | 880/1267 [38:17<16:49,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 70%|██████████████████████████████████████████████████████▉                        | 881/1267 [38:20<16:52,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 70%|██████████████████████████████████████████████████████▉                        | 882/1267 [38:23<16:48,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 70%|███████████████████████████████████████████████████████                        | 883/1267 [38:25<16:49,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 228886

 70%|███████████████████████████████████████████████████████                        | 884/1267 [38:28<16:52,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 150590

 70%|███████████████████████████████████████████████████████▏                       | 885/1267 [38:31<16:51,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 70%|███████████████████████████████████████████████████████▏                       | 886/1267 [38:33<16:42,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 111100

 70%|███████████████████████████████████████████████████████▎                       | 887/1267 [38:36<16:32,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 21097

 70%|███████████████████████████████████████████████████████▎                       | 888/1267 [38:38<16:19,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 70%|███████████████████████████████████████████████████████▍                       | 889/1267 [38:41<16:06,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 70%|███████████████████████████████████████████████████████▍                       | 890/1267 [38:43<16:01,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 70%|███████████████████████████████████████████████████████▌                       | 891/1267 [38:46<15:53,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 70%|███████████████████████████████████████████████████████▌                       | 892/1267 [38:49<15:52,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 225461

 70%|███████████████████████████████████████████████████████▋                       | 893/1267 [38:51<15:58,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 147848

 71%|███████████████████████████████████████████████████████▋                       | 894/1267 [38:54<15:53,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 71%|███████████████████████████████████████████████████████▊                       | 895/1267 [38:56<15:46,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 102800

 71%|███████████████████████████████████████████████████████▊                       | 896/1267 [38:59<15:39,  2.53s/it]

Created 300 windows of shape (128, 4) from sequence of length 27997

 71%|███████████████████████████████████████████████████████▉                       | 897/1267 [39:01<15:39,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 71%|███████████████████████████████████████████████████████▉                       | 898/1267 [39:04<15:34,  2.53s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 71%|████████████████████████████████████████████████████████                       | 899/1267 [39:06<15:30,  2.53s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 71%|████████████████████████████████████████████████████████                       | 900/1267 [39:09<15:29,  2.53s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 71%|████████████████████████████████████████████████████████▏                      | 901/1267 [39:11<15:30,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 71%|████████████████████████████████████████████████████████▏                      | 902/1267 [39:14<15:26,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 71%|████████████████████████████████████████████████████████▎                      | 903/1267 [39:16<15:22,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 71%|████████████████████████████████████████████████████████▎                      | 904/1267 [39:19<15:23,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 71%|████████████████████████████████████████████████████████▍                      | 905/1267 [39:22<15:23,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 72%|████████████████████████████████████████████████████████▍                      | 906/1267 [39:24<15:16,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 72%|████████████████████████████████████████████████████████▌                      | 907/1267 [39:27<15:15,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 72%|████████████████████████████████████████████████████████▌                      | 908/1267 [39:29<15:24,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 72%|████████████████████████████████████████████████████████▋                      | 909/1267 [39:32<15:29,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 72%|████████████████████████████████████████████████████████▋                      | 910/1267 [39:35<15:29,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 72%|████████████████████████████████████████████████████████▊                      | 911/1267 [39:37<15:23,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 72%|████████████████████████████████████████████████████████▊                      | 912/1267 [39:40<15:22,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 72%|████████████████████████████████████████████████████████▉                      | 913/1267 [39:42<15:16,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 222583

 72%|████████████████████████████████████████████████████████▉                      | 914/1267 [39:45<15:19,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 153377

 72%|█████████████████████████████████████████████████████████                      | 915/1267 [39:47<15:06,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 72%|█████████████████████████████████████████████████████████                      | 916/1267 [39:50<15:09,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 109000

 72%|█████████████████████████████████████████████████████████▏                     | 917/1267 [39:53<15:07,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 30998

 72%|█████████████████████████████████████████████████████████▏                     | 918/1267 [39:55<14:58,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 73%|█████████████████████████████████████████████████████████▎                     | 919/1267 [39:58<14:49,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 73%|█████████████████████████████████████████████████████████▎                     | 920/1267 [40:00<14:52,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 73%|█████████████████████████████████████████████████████████▍                     | 921/1267 [40:03<14:55,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 73%|█████████████████████████████████████████████████████████▍                     | 922/1267 [40:06<15:01,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 235419

 73%|█████████████████████████████████████████████████████████▌                     | 923/1267 [40:08<14:54,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 149607

 73%|█████████████████████████████████████████████████████████▌                     | 924/1267 [40:11<14:45,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 73%|█████████████████████████████████████████████████████████▋                     | 925/1267 [40:13<14:45,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 100600

 73%|█████████████████████████████████████████████████████████▋                     | 926/1267 [40:16<14:36,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 32098

 73%|█████████████████████████████████████████████████████████▊                     | 927/1267 [40:18<14:39,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 73%|█████████████████████████████████████████████████████████▊                     | 928/1267 [40:21<14:41,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 73%|█████████████████████████████████████████████████████████▉                     | 929/1267 [40:24<14:38,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 73%|█████████████████████████████████████████████████████████▉                     | 930/1267 [40:26<14:37,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 73%|██████████████████████████████████████████████████████████                     | 931/1267 [40:29<14:35,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 230313

 74%|██████████████████████████████████████████████████████████                     | 932/1267 [40:32<14:29,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 150182

 74%|██████████████████████████████████████████████████████████▏                    | 933/1267 [40:34<14:21,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 30592

 74%|██████████████████████████████████████████████████████████▏                    | 934/1267 [40:37<14:19,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 96100

 74%|██████████████████████████████████████████████████████████▎                    | 935/1267 [40:39<14:12,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 32898

 74%|██████████████████████████████████████████████████████████▎                    | 936/1267 [40:42<14:04,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 74%|██████████████████████████████████████████████████████████▍                    | 937/1267 [40:44<13:53,  2.53s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 74%|██████████████████████████████████████████████████████████▍                    | 938/1267 [40:47<13:55,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 74%|██████████████████████████████████████████████████████████▌                    | 939/1267 [40:49<13:51,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 74%|██████████████████████████████████████████████████████████▌                    | 940/1267 [40:52<13:47,  2.53s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 74%|██████████████████████████████████████████████████████████▋                    | 941/1267 [40:54<13:46,  2.53s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 74%|██████████████████████████████████████████████████████████▋                    | 942/1267 [40:57<13:44,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 74%|██████████████████████████████████████████████████████████▊                    | 943/1267 [40:59<13:44,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 75%|██████████████████████████████████████████████████████████▊                    | 944/1267 [41:02<13:47,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 75%|██████████████████████████████████████████████████████████▉                    | 945/1267 [41:05<13:48,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 75%|██████████████████████████████████████████████████████████▉                    | 946/1267 [41:07<13:53,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 75%|███████████████████████████████████████████████████████████                    | 947/1267 [41:10<13:55,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 75%|███████████████████████████████████████████████████████████                    | 948/1267 [41:13<13:56,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 75%|███████████████████████████████████████████████████████████▏                   | 949/1267 [41:15<13:56,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 75%|███████████████████████████████████████████████████████████▏                   | 950/1267 [41:18<13:55,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 75%|███████████████████████████████████████████████████████████▎                   | 951/1267 [41:20<13:50,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 75%|███████████████████████████████████████████████████████████▎                   | 952/1267 [41:23<13:48,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 226896

 75%|███████████████████████████████████████████████████████████▍                   | 953/1267 [41:26<13:49,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 147189

 75%|███████████████████████████████████████████████████████████▍                   | 954/1267 [41:28<13:43,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 30592

 75%|███████████████████████████████████████████████████████████▌                   | 955/1267 [41:31<13:37,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 110400

 75%|███████████████████████████████████████████████████████████▌                   | 956/1267 [41:34<13:34,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 21997

 76%|███████████████████████████████████████████████████████████▋                   | 957/1267 [41:36<13:34,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 76%|███████████████████████████████████████████████████████████▋                   | 958/1267 [41:39<13:28,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 76%|███████████████████████████████████████████████████████████▊                   | 959/1267 [41:41<13:22,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 76%|███████████████████████████████████████████████████████████▊                   | 960/1267 [41:44<13:19,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 76%|███████████████████████████████████████████████████████████▉                   | 961/1267 [41:47<13:14,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 229185

 76%|███████████████████████████████████████████████████████████▉                   | 962/1267 [41:49<13:06,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 150429

 76%|████████████████████████████████████████████████████████████                   | 963/1267 [41:52<13:04,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 30592

 76%|████████████████████████████████████████████████████████████                   | 964/1267 [41:54<12:58,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 107700

 76%|████████████████████████████████████████████████████████████▏                  | 965/1267 [41:57<12:57,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 21497

 76%|████████████████████████████████████████████████████████████▏                  | 966/1267 [41:59<12:53,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 76%|████████████████████████████████████████████████████████████▎                  | 967/1267 [42:02<12:54,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 76%|████████████████████████████████████████████████████████████▎                  | 968/1267 [42:05<12:48,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 76%|████████████████████████████████████████████████████████████▍                  | 969/1267 [42:07<12:49,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 77%|████████████████████████████████████████████████████████████▍                  | 970/1267 [42:10<12:47,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 228869

 77%|████████████████████████████████████████████████████████████▌                  | 971/1267 [42:12<12:49,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 151281

 77%|████████████████████████████████████████████████████████████▌                  | 972/1267 [42:15<12:51,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 77%|████████████████████████████████████████████████████████████▋                  | 973/1267 [42:18<12:50,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 106600

 77%|████████████████████████████████████████████████████████████▋                  | 974/1267 [42:20<12:49,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 25298

 77%|████████████████████████████████████████████████████████████▊                  | 975/1267 [42:23<12:44,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 77%|████████████████████████████████████████████████████████████▊                  | 976/1267 [42:26<12:42,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 77%|████████████████████████████████████████████████████████████▉                  | 977/1267 [42:28<12:39,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 77%|████████████████████████████████████████████████████████████▉                  | 978/1267 [42:31<12:35,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 77%|█████████████████████████████████████████████████████████████                  | 979/1267 [42:33<12:36,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 77%|█████████████████████████████████████████████████████████████                  | 980/1267 [42:36<12:31,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 77%|█████████████████████████████████████████████████████████████▏                 | 981/1267 [42:39<12:24,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 78%|█████████████████████████████████████████████████████████████▏                 | 982/1267 [42:41<12:16,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 78%|█████████████████████████████████████████████████████████████▎                 | 983/1267 [42:44<12:12,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 78%|█████████████████████████████████████████████████████████████▎                 | 984/1267 [42:46<12:01,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 78%|█████████████████████████████████████████████████████████████▍                 | 985/1267 [42:49<12:03,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 78%|█████████████████████████████████████████████████████████████▍                 | 986/1267 [42:51<11:58,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 78%|█████████████████████████████████████████████████████████████▌                 | 987/1267 [42:54<11:56,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 78%|█████████████████████████████████████████████████████████████▌                 | 988/1267 [42:56<11:53,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 78%|█████████████████████████████████████████████████████████████▋                 | 989/1267 [42:59<11:53,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 78%|█████████████████████████████████████████████████████████████▋                 | 990/1267 [43:02<11:46,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 78%|█████████████████████████████████████████████████████████████▊                 | 991/1267 [43:04<11:48,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 78%|█████████████████████████████████████████████████████████████▊                 | 992/1267 [43:07<11:48,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 78%|█████████████████████████████████████████████████████████████▉                 | 993/1267 [43:09<11:51,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 78%|█████████████████████████████████████████████████████████████▉                 | 994/1267 [43:12<11:50,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 79%|██████████████████████████████████████████████████████████████                 | 995/1267 [43:15<11:53,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 228886

 79%|██████████████████████████████████████████████████████████████                 | 996/1267 [43:17<11:53,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 150590

 79%|██████████████████████████████████████████████████████████████▏                | 997/1267 [43:20<11:55,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 79%|██████████████████████████████████████████████████████████████▏                | 998/1267 [43:23<11:46,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 111100

 79%|██████████████████████████████████████████████████████████████▎                | 999/1267 [43:25<11:35,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 21097

 79%|█████████████████████████████████████████████████████████████▌                | 1000/1267 [43:28<11:36,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 79%|█████████████████████████████████████████████████████████████▌                | 1001/1267 [43:30<11:33,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 79%|█████████████████████████████████████████████████████████████▋                | 1002/1267 [43:33<11:34,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 79%|█████████████████████████████████████████████████████████████▋                | 1003/1267 [43:36<11:31,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 79%|█████████████████████████████████████████████████████████████▊                | 1004/1267 [43:38<11:28,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 225461

 79%|█████████████████████████████████████████████████████████████▊                | 1005/1267 [43:41<11:32,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 147848

 79%|█████████████████████████████████████████████████████████████▉                | 1006/1267 [43:44<11:29,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 79%|█████████████████████████████████████████████████████████████▉                | 1007/1267 [43:46<11:24,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 102800

 80%|██████████████████████████████████████████████████████████████                | 1008/1267 [43:49<11:14,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 27997

 80%|██████████████████████████████████████████████████████████████                | 1009/1267 [43:51<11:11,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 80%|██████████████████████████████████████████████████████████████▏               | 1010/1267 [43:54<11:09,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 80%|██████████████████████████████████████████████████████████████▏               | 1011/1267 [43:56<11:02,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 80%|██████████████████████████████████████████████████████████████▎               | 1012/1267 [43:59<10:54,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 80%|██████████████████████████████████████████████████████████████▎               | 1013/1267 [44:02<10:53,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 80%|██████████████████████████████████████████████████████████████▍               | 1014/1267 [44:04<10:53,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 80%|██████████████████████████████████████████████████████████████▍               | 1015/1267 [44:07<10:53,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 80%|██████████████████████████████████████████████████████████████▌               | 1016/1267 [44:09<10:57,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 80%|██████████████████████████████████████████████████████████████▌               | 1017/1267 [44:12<10:57,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 80%|██████████████████████████████████████████████████████████████▋               | 1018/1267 [44:15<11:03,  2.66s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 80%|██████████████████████████████████████████████████████████████▋               | 1019/1267 [44:18<11:03,  2.67s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 81%|██████████████████████████████████████████████████████████████▊               | 1020/1267 [44:20<11:02,  2.68s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 81%|██████████████████████████████████████████████████████████████▊               | 1021/1267 [44:23<11:01,  2.69s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 81%|██████████████████████████████████████████████████████████████▉               | 1022/1267 [44:26<10:59,  2.69s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 81%|██████████████████████████████████████████████████████████████▉               | 1023/1267 [44:28<10:57,  2.69s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 81%|███████████████████████████████████████████████████████████████               | 1024/1267 [44:31<10:55,  2.70s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 81%|███████████████████████████████████████████████████████████████               | 1025/1267 [44:34<10:53,  2.70s/it]

Created 300 windows of shape (128, 4) from sequence of length 222583

 81%|███████████████████████████████████████████████████████████████▏              | 1026/1267 [44:36<10:42,  2.67s/it]

Created 300 windows of shape (128, 4) from sequence of length 153377

 81%|███████████████████████████████████████████████████████████████▏              | 1027/1267 [44:39<10:36,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 81%|███████████████████████████████████████████████████████████████▎              | 1028/1267 [44:42<10:35,  2.66s/it]

Created 300 windows of shape (128, 4) from sequence of length 109000

 81%|███████████████████████████████████████████████████████████████▎              | 1029/1267 [44:44<10:35,  2.67s/it]

Created 300 windows of shape (128, 4) from sequence of length 30998

 81%|███████████████████████████████████████████████████████████████▍              | 1030/1267 [44:47<10:33,  2.67s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 81%|███████████████████████████████████████████████████████████████▍              | 1031/1267 [44:50<10:28,  2.66s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 81%|███████████████████████████████████████████████████████████████▌              | 1032/1267 [44:52<10:25,  2.66s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 82%|███████████████████████████████████████████████████████████████▌              | 1033/1267 [44:55<10:25,  2.67s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 82%|███████████████████████████████████████████████████████████████▋              | 1034/1267 [44:58<10:18,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 235419

 82%|███████████████████████████████████████████████████████████████▋              | 1035/1267 [45:00<10:10,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 149607

 82%|███████████████████████████████████████████████████████████████▊              | 1036/1267 [45:03<09:59,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 82%|███████████████████████████████████████████████████████████████▊              | 1037/1267 [45:05<09:51,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 100600

 82%|███████████████████████████████████████████████████████████████▉              | 1038/1267 [45:08<09:50,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 32098

 82%|███████████████████████████████████████████████████████████████▉              | 1039/1267 [45:11<09:58,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 82%|████████████████████████████████████████████████████████████████              | 1040/1267 [45:13<10:00,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 82%|████████████████████████████████████████████████████████████████              | 1041/1267 [45:16<10:01,  2.66s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 82%|████████████████████████████████████████████████████████████████▏             | 1042/1267 [45:19<09:59,  2.67s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 82%|████████████████████████████████████████████████████████████████▏             | 1043/1267 [45:21<09:55,  2.66s/it]

Created 300 windows of shape (128, 4) from sequence of length 230313

 82%|████████████████████████████████████████████████████████████████▎             | 1044/1267 [45:24<09:52,  2.66s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 82%|████████████████████████████████████████████████████████████████▎             | 1045/1267 [45:27<09:45,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 83%|████████████████████████████████████████████████████████████████▍             | 1046/1267 [45:29<09:38,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 83%|████████████████████████████████████████████████████████████████▍             | 1047/1267 [45:32<09:31,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 83%|████████████████████████████████████████████████████████████████▌             | 1048/1267 [45:34<09:25,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 83%|████████████████████████████████████████████████████████████████▌             | 1049/1267 [45:37<09:17,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 83%|████████████████████████████████████████████████████████████████▋             | 1050/1267 [45:39<09:11,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 83%|████████████████████████████████████████████████████████████████▋             | 1051/1267 [45:42<09:05,  2.53s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 83%|████████████████████████████████████████████████████████████████▊             | 1052/1267 [45:44<09:05,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 83%|████████████████████████████████████████████████████████████████▊             | 1053/1267 [45:47<09:04,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 83%|████████████████████████████████████████████████████████████████▉             | 1054/1267 [45:49<09:03,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 83%|████████████████████████████████████████████████████████████████▉             | 1055/1267 [45:52<09:00,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 83%|█████████████████████████████████████████████████████████████████             | 1056/1267 [45:55<09:01,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 83%|█████████████████████████████████████████████████████████████████             | 1057/1267 [45:57<09:00,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 84%|█████████████████████████████████████████████████████████████████▏            | 1058/1267 [46:00<08:58,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 84%|█████████████████████████████████████████████████████████████████▏            | 1059/1267 [46:02<08:56,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 84%|█████████████████████████████████████████████████████████████████▎            | 1060/1267 [46:05<08:56,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 222583

 84%|█████████████████████████████████████████████████████████████████▎            | 1061/1267 [46:08<09:03,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 153377

 84%|█████████████████████████████████████████████████████████████████▍            | 1062/1267 [46:10<09:02,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 84%|█████████████████████████████████████████████████████████████████▍            | 1063/1267 [46:13<09:04,  2.67s/it]

Created 300 windows of shape (128, 4) from sequence of length 109000

 84%|█████████████████████████████████████████████████████████████████▌            | 1064/1267 [46:16<09:02,  2.67s/it]

Created 300 windows of shape (128, 4) from sequence of length 30998

 84%|█████████████████████████████████████████████████████████████████▌            | 1065/1267 [46:18<09:02,  2.69s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 84%|█████████████████████████████████████████████████████████████████▋            | 1066/1267 [46:21<09:03,  2.70s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 84%|█████████████████████████████████████████████████████████████████▋            | 1067/1267 [46:24<09:00,  2.70s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 84%|█████████████████████████████████████████████████████████████████▋            | 1068/1267 [46:27<09:03,  2.73s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 84%|█████████████████████████████████████████████████████████████████▊            | 1069/1267 [46:29<08:56,  2.71s/it]

Created 300 windows of shape (128, 4) from sequence of length 235419

 84%|█████████████████████████████████████████████████████████████████▊            | 1070/1267 [46:32<08:51,  2.70s/it]

Created 300 windows of shape (128, 4) from sequence of length 149607

 85%|█████████████████████████████████████████████████████████████████▉            | 1071/1267 [46:35<08:45,  2.68s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 85%|█████████████████████████████████████████████████████████████████▉            | 1072/1267 [46:37<08:34,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 100600

 85%|██████████████████████████████████████████████████████████████████            | 1073/1267 [46:40<08:29,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 32098

 85%|██████████████████████████████████████████████████████████████████            | 1074/1267 [46:42<08:24,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 85%|██████████████████████████████████████████████████████████████████▏           | 1075/1267 [46:45<08:22,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 85%|██████████████████████████████████████████████████████████████████▏           | 1076/1267 [46:48<08:20,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 85%|██████████████████████████████████████████████████████████████████▎           | 1077/1267 [46:50<08:17,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 85%|██████████████████████████████████████████████████████████████████▎           | 1078/1267 [46:53<08:14,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 230313

 85%|██████████████████████████████████████████████████████████████████▍           | 1079/1267 [46:55<08:10,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 150182

 85%|██████████████████████████████████████████████████████████████████▍           | 1080/1267 [46:58<08:04,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 30592

 85%|██████████████████████████████████████████████████████████████████▌           | 1081/1267 [47:01<07:58,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 96100

 85%|██████████████████████████████████████████████████████████████████▌           | 1082/1267 [47:03<07:53,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 32898

 85%|██████████████████████████████████████████████████████████████████▋           | 1083/1267 [47:06<07:53,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 86%|██████████████████████████████████████████████████████████████████▋           | 1084/1267 [47:08<07:49,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 86%|██████████████████████████████████████████████████████████████████▊           | 1085/1267 [47:11<07:47,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 86%|██████████████████████████████████████████████████████████████████▊           | 1086/1267 [47:13<07:46,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 86%|██████████████████████████████████████████████████████████████████▉           | 1087/1267 [47:16<07:44,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 86%|██████████████████████████████████████████████████████████████████▉           | 1088/1267 [47:19<07:42,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 86%|███████████████████████████████████████████████████████████████████           | 1089/1267 [47:21<07:42,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 86%|███████████████████████████████████████████████████████████████████           | 1090/1267 [47:24<07:39,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 86%|███████████████████████████████████████████████████████████████████▏          | 1091/1267 [47:26<07:35,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 86%|███████████████████████████████████████████████████████████████████▏          | 1092/1267 [47:29<07:37,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 86%|███████████████████████████████████████████████████████████████████▎          | 1093/1267 [47:32<07:34,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 86%|███████████████████████████████████████████████████████████████████▎          | 1094/1267 [47:34<07:31,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 86%|███████████████████████████████████████████████████████████████████▍          | 1095/1267 [47:37<07:28,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 87%|███████████████████████████████████████████████████████████████████▍          | 1096/1267 [47:39<07:24,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 87%|███████████████████████████████████████████████████████████████████▌          | 1097/1267 [47:42<07:22,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 87%|███████████████████████████████████████████████████████████████████▌          | 1098/1267 [47:45<07:16,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 87%|███████████████████████████████████████████████████████████████████▋          | 1099/1267 [47:47<07:12,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 226896

 87%|███████████████████████████████████████████████████████████████████▋          | 1100/1267 [47:50<07:12,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 147189

 87%|███████████████████████████████████████████████████████████████████▊          | 1101/1267 [47:52<07:05,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 30592

 87%|███████████████████████████████████████████████████████████████████▊          | 1102/1267 [47:55<07:01,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 110400

 87%|███████████████████████████████████████████████████████████████████▉          | 1103/1267 [47:57<06:57,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 21997

 87%|███████████████████████████████████████████████████████████████████▉          | 1104/1267 [48:00<06:55,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 87%|████████████████████████████████████████████████████████████████████          | 1105/1267 [48:03<06:56,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 87%|████████████████████████████████████████████████████████████████████          | 1106/1267 [48:05<06:53,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 87%|████████████████████████████████████████████████████████████████████▏         | 1107/1267 [48:08<06:50,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 87%|████████████████████████████████████████████████████████████████████▏         | 1108/1267 [48:10<06:49,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 229185

 88%|████████████████████████████████████████████████████████████████████▎         | 1109/1267 [48:13<06:46,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 150429

 88%|████████████████████████████████████████████████████████████████████▎         | 1110/1267 [48:15<06:42,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 30592

 88%|████████████████████████████████████████████████████████████████████▍         | 1111/1267 [48:18<06:40,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 107700

 88%|████████████████████████████████████████████████████████████████████▍         | 1112/1267 [48:21<06:38,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 21497

 88%|████████████████████████████████████████████████████████████████████▌         | 1113/1267 [48:23<06:33,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 88%|████████████████████████████████████████████████████████████████████▌         | 1114/1267 [48:26<06:30,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 88%|████████████████████████████████████████████████████████████████████▋         | 1115/1267 [48:28<06:30,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 88%|████████████████████████████████████████████████████████████████████▋         | 1116/1267 [48:31<06:26,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 88%|████████████████████████████████████████████████████████████████████▊         | 1117/1267 [48:33<06:25,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 228869

 88%|████████████████████████████████████████████████████████████████████▊         | 1118/1267 [48:36<06:23,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 151281

 88%|████████████████████████████████████████████████████████████████████▉         | 1119/1267 [48:38<06:21,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 88%|████████████████████████████████████████████████████████████████████▉         | 1120/1267 [48:41<06:18,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 106600

 88%|█████████████████████████████████████████████████████████████████████         | 1121/1267 [48:44<06:15,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 25298

 89%|█████████████████████████████████████████████████████████████████████         | 1122/1267 [48:46<06:14,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 89%|█████████████████████████████████████████████████████████████████████▏        | 1123/1267 [48:49<06:13,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 89%|█████████████████████████████████████████████████████████████████████▏        | 1124/1267 [48:52<06:13,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 89%|█████████████████████████████████████████████████████████████████████▎        | 1125/1267 [48:54<06:11,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 89%|█████████████████████████████████████████████████████████████████████▎        | 1126/1267 [48:57<06:10,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 89%|█████████████████████████████████████████████████████████████████████▍        | 1127/1267 [48:59<06:07,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 89%|█████████████████████████████████████████████████████████████████████▍        | 1128/1267 [49:02<06:03,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 89%|█████████████████████████████████████████████████████████████████████▌        | 1129/1267 [49:05<05:59,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 89%|█████████████████████████████████████████████████████████████████████▌        | 1130/1267 [49:07<05:54,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 89%|█████████████████████████████████████████████████████████████████████▋        | 1131/1267 [49:10<05:50,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 89%|█████████████████████████████████████████████████████████████████████▋        | 1132/1267 [49:12<05:49,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 89%|█████████████████████████████████████████████████████████████████████▊        | 1133/1267 [49:15<05:48,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 90%|█████████████████████████████████████████████████████████████████████▊        | 1134/1267 [49:18<05:45,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 90%|█████████████████████████████████████████████████████████████████████▊        | 1135/1267 [49:20<05:43,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 90%|█████████████████████████████████████████████████████████████████████▉        | 1136/1267 [49:23<05:41,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 90%|█████████████████████████████████████████████████████████████████████▉        | 1137/1267 [49:25<05:36,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 90%|██████████████████████████████████████████████████████████████████████        | 1138/1267 [49:28<05:33,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 90%|██████████████████████████████████████████████████████████████████████        | 1139/1267 [49:30<05:30,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 90%|██████████████████████████████████████████████████████████████████████▏       | 1140/1267 [49:33<05:30,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 90%|██████████████████████████████████████████████████████████████████████▏       | 1141/1267 [49:36<05:28,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 90%|██████████████████████████████████████████████████████████████████████▎       | 1142/1267 [49:38<05:20,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 228886

 90%|██████████████████████████████████████████████████████████████████████▎       | 1143/1267 [49:41<05:18,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 150590

 90%|██████████████████████████████████████████████████████████████████████▍       | 1144/1267 [49:43<05:12,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 90%|██████████████████████████████████████████████████████████████████████▍       | 1145/1267 [49:46<05:09,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 111100

 90%|██████████████████████████████████████████████████████████████████████▌       | 1146/1267 [49:48<05:06,  2.53s/it]

Created 300 windows of shape (128, 4) from sequence of length 21097

 91%|██████████████████████████████████████████████████████████████████████▌       | 1147/1267 [49:51<05:02,  2.52s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 91%|██████████████████████████████████████████████████████████████████████▋       | 1148/1267 [49:53<04:59,  2.52s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 91%|██████████████████████████████████████████████████████████████████████▋       | 1149/1267 [49:56<04:59,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 91%|██████████████████████████████████████████████████████████████████████▊       | 1150/1267 [49:58<04:58,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 91%|██████████████████████████████████████████████████████████████████████▊       | 1151/1267 [50:01<04:56,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 225461

 91%|██████████████████████████████████████████████████████████████████████▉       | 1152/1267 [50:04<04:54,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 147848

 91%|██████████████████████████████████████████████████████████████████████▉       | 1153/1267 [50:06<04:55,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 91%|███████████████████████████████████████████████████████████████████████       | 1154/1267 [50:09<04:59,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 102800

 91%|███████████████████████████████████████████████████████████████████████       | 1155/1267 [50:12<04:58,  2.67s/it]

Created 300 windows of shape (128, 4) from sequence of length 27997

 91%|███████████████████████████████████████████████████████████████████████▏      | 1156/1267 [50:14<04:57,  2.68s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 91%|███████████████████████████████████████████████████████████████████████▏      | 1157/1267 [50:17<04:53,  2.66s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 91%|███████████████████████████████████████████████████████████████████████▎      | 1158/1267 [50:20<04:48,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 91%|███████████████████████████████████████████████████████████████████████▎      | 1159/1267 [50:22<04:41,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 92%|███████████████████████████████████████████████████████████████████████▍      | 1160/1267 [50:25<04:34,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 92%|███████████████████████████████████████████████████████████████████████▍      | 1161/1267 [50:27<04:29,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 92%|███████████████████████████████████████████████████████████████████████▌      | 1162/1267 [50:30<04:29,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 92%|███████████████████████████████████████████████████████████████████████▌      | 1163/1267 [50:32<04:28,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 92%|███████████████████████████████████████████████████████████████████████▋      | 1164/1267 [50:35<04:30,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 92%|███████████████████████████████████████████████████████████████████████▋      | 1165/1267 [50:38<04:28,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 92%|███████████████████████████████████████████████████████████████████████▊      | 1166/1267 [50:40<04:24,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 92%|███████████████████████████████████████████████████████████████████████▊      | 1167/1267 [50:43<04:21,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 92%|███████████████████████████████████████████████████████████████████████▉      | 1168/1267 [50:46<04:19,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 92%|███████████████████████████████████████████████████████████████████████▉      | 1169/1267 [50:48<04:17,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 92%|████████████████████████████████████████████████████████████████████████      | 1170/1267 [50:51<04:13,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 92%|████████████████████████████████████████████████████████████████████████      | 1171/1267 [50:53<04:11,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 93%|████████████████████████████████████████████████████████████████████████▏     | 1172/1267 [50:56<04:09,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 222583

 93%|████████████████████████████████████████████████████████████████████████▏     | 1173/1267 [50:59<04:01,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 153377

 93%|████████████████████████████████████████████████████████████████████████▎     | 1174/1267 [51:01<03:58,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 93%|████████████████████████████████████████████████████████████████████████▎     | 1175/1267 [51:04<03:54,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 109000

 93%|████████████████████████████████████████████████████████████████████████▍     | 1176/1267 [51:06<03:51,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 30998

 93%|████████████████████████████████████████████████████████████████████████▍     | 1177/1267 [51:09<03:52,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 93%|████████████████████████████████████████████████████████████████████████▌     | 1178/1267 [51:12<03:52,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 93%|████████████████████████████████████████████████████████████████████████▌     | 1179/1267 [51:14<03:51,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 93%|████████████████████████████████████████████████████████████████████████▋     | 1180/1267 [51:17<03:50,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 93%|████████████████████████████████████████████████████████████████████████▋     | 1181/1267 [51:20<03:47,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 235419

 93%|████████████████████████████████████████████████████████████████████████▊     | 1182/1267 [51:22<03:42,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 149607

 93%|████████████████████████████████████████████████████████████████████████▊     | 1183/1267 [51:25<03:39,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 93%|████████████████████████████████████████████████████████████████████████▉     | 1184/1267 [51:27<03:37,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 100600

 94%|████████████████████████████████████████████████████████████████████████▉     | 1185/1267 [51:30<03:35,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 32098

 94%|█████████████████████████████████████████████████████████████████████████     | 1186/1267 [51:33<03:33,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 94%|█████████████████████████████████████████████████████████████████████████     | 1187/1267 [51:35<03:31,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 94%|█████████████████████████████████████████████████████████████████████████▏    | 1188/1267 [51:38<03:28,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 94%|█████████████████████████████████████████████████████████████████████████▏    | 1189/1267 [51:40<03:24,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 94%|█████████████████████████████████████████████████████████████████████████▎    | 1190/1267 [51:43<03:20,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 230313

 94%|█████████████████████████████████████████████████████████████████████████▎    | 1191/1267 [51:46<03:16,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 150182

 94%|█████████████████████████████████████████████████████████████████████████▍    | 1192/1267 [51:48<03:13,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 30592

 94%|█████████████████████████████████████████████████████████████████████████▍    | 1193/1267 [51:51<03:09,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 96100

 94%|█████████████████████████████████████████████████████████████████████████▌    | 1194/1267 [51:53<03:06,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 32898

 94%|█████████████████████████████████████████████████████████████████████████▌    | 1195/1267 [51:56<03:04,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 94%|█████████████████████████████████████████████████████████████████████████▋    | 1196/1267 [51:58<03:03,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 94%|█████████████████████████████████████████████████████████████████████████▋    | 1197/1267 [52:01<03:00,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 95%|█████████████████████████████████████████████████████████████████████████▊    | 1198/1267 [52:04<02:57,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 95%|█████████████████████████████████████████████████████████████████████████▊    | 1199/1267 [52:06<02:55,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 95%|█████████████████████████████████████████████████████████████████████████▉    | 1200/1267 [52:09<02:54,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 95%|█████████████████████████████████████████████████████████████████████████▉    | 1201/1267 [52:11<02:53,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 95%|█████████████████████████████████████████████████████████████████████████▉    | 1202/1267 [52:14<02:50,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 95%|██████████████████████████████████████████████████████████████████████████    | 1203/1267 [52:17<02:49,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 95%|██████████████████████████████████████████████████████████████████████████    | 1204/1267 [52:19<02:46,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 95%|██████████████████████████████████████████████████████████████████████████▏   | 1205/1267 [52:22<02:43,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 95%|██████████████████████████████████████████████████████████████████████████▏   | 1206/1267 [52:25<02:40,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 95%|██████████████████████████████████████████████████████████████████████████▎   | 1207/1267 [52:27<02:38,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 95%|██████████████████████████████████████████████████████████████████████████▎   | 1208/1267 [52:30<02:36,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 95%|██████████████████████████████████████████████████████████████████████████▍   | 1209/1267 [52:33<02:34,  2.66s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 96%|██████████████████████████████████████████████████████████████████████████▍   | 1210/1267 [52:35<02:31,  2.67s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 96%|██████████████████████████████████████████████████████████████████████████▌   | 1211/1267 [52:38<02:28,  2.65s/it]

Created 300 windows of shape (128, 4) from sequence of length 226896

 96%|██████████████████████████████████████████████████████████████████████████▌   | 1212/1267 [52:41<02:25,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 147189

 96%|██████████████████████████████████████████████████████████████████████████▋   | 1213/1267 [52:43<02:22,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 30592

 96%|██████████████████████████████████████████████████████████████████████████▋   | 1214/1267 [52:46<02:19,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 110400

 96%|██████████████████████████████████████████████████████████████████████████▊   | 1215/1267 [52:48<02:16,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 21997

 96%|██████████████████████████████████████████████████████████████████████████▊   | 1216/1267 [52:51<02:13,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 96%|██████████████████████████████████████████████████████████████████████████▉   | 1217/1267 [52:54<02:10,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 96%|██████████████████████████████████████████████████████████████████████████▉   | 1218/1267 [52:56<02:09,  2.64s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 96%|███████████████████████████████████████████████████████████████████████████   | 1219/1267 [52:59<02:06,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 96%|███████████████████████████████████████████████████████████████████████████   | 1220/1267 [53:02<02:03,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 229185

 96%|███████████████████████████████████████████████████████████████████████████▏  | 1221/1267 [53:04<02:01,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 150429

 96%|███████████████████████████████████████████████████████████████████████████▏  | 1222/1267 [53:07<01:57,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 30592

 97%|███████████████████████████████████████████████████████████████████████████▎  | 1223/1267 [53:09<01:55,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 107700

 97%|███████████████████████████████████████████████████████████████████████████▎  | 1224/1267 [53:12<01:52,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 21497

 97%|███████████████████████████████████████████████████████████████████████████▍  | 1225/1267 [53:15<01:50,  2.63s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 97%|███████████████████████████████████████████████████████████████████████████▍  | 1226/1267 [53:17<01:47,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 97%|███████████████████████████████████████████████████████████████████████████▌  | 1227/1267 [53:20<01:44,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 97%|███████████████████████████████████████████████████████████████████████████▌  | 1228/1267 [53:22<01:41,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 97%|███████████████████████████████████████████████████████████████████████████▋  | 1229/1267 [53:25<01:38,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 228869

 97%|███████████████████████████████████████████████████████████████████████████▋  | 1230/1267 [53:28<01:36,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 151281

 97%|███████████████████████████████████████████████████████████████████████████▊  | 1231/1267 [53:30<01:34,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 97%|███████████████████████████████████████████████████████████████████████████▊  | 1232/1267 [53:33<01:31,  2.62s/it]

Created 300 windows of shape (128, 4) from sequence of length 106600

 97%|███████████████████████████████████████████████████████████████████████████▉  | 1233/1267 [53:36<01:28,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 25298

 97%|███████████████████████████████████████████████████████████████████████████▉  | 1234/1267 [53:38<01:25,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 97%|████████████████████████████████████████████████████████████████████████████  | 1235/1267 [53:41<01:22,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 98%|████████████████████████████████████████████████████████████████████████████  | 1236/1267 [53:43<01:19,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 98%|████████████████████████████████████████████████████████████████████████████▏ | 1237/1267 [53:46<01:16,  2.53s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 98%|████████████████████████████████████████████████████████████████████████████▏ | 1238/1267 [53:48<01:13,  2.53s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 98%|████████████████████████████████████████████████████████████████████████████▎ | 1239/1267 [53:51<01:10,  2.52s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 98%|████████████████████████████████████████████████████████████████████████████▎ | 1240/1267 [53:53<01:07,  2.51s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 98%|████████████████████████████████████████████████████████████████████████████▍ | 1241/1267 [53:56<01:06,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 98%|████████████████████████████████████████████████████████████████████████████▍ | 1242/1267 [53:58<01:03,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 98%|████████████████████████████████████████████████████████████████████████████▌ | 1243/1267 [54:01<01:01,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 98%|████████████████████████████████████████████████████████████████████████████▌ | 1244/1267 [54:03<00:58,  2.54s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 98%|████████████████████████████████████████████████████████████████████████████▋ | 1245/1267 [54:06<00:56,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 98%|████████████████████████████████████████████████████████████████████████████▋ | 1246/1267 [54:09<00:54,  2.59s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 98%|████████████████████████████████████████████████████████████████████████████▊ | 1247/1267 [54:11<00:51,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 30600

 99%|████████████████████████████████████████████████████████████████████████████▊ | 1248/1267 [54:14<00:49,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 99%|████████████████████████████████████████████████████████████████████████████▉ | 1249/1267 [54:16<00:46,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 63300

 99%|████████████████████████████████████████████████████████████████████████████▉ | 1250/1267 [54:19<00:44,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 99%|█████████████████████████████████████████████████████████████████████████████ | 1251/1267 [54:22<00:41,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

 99%|█████████████████████████████████████████████████████████████████████████████ | 1252/1267 [54:24<00:39,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

 99%|█████████████████████████████████████████████████████████████████████████████▏| 1253/1267 [54:27<00:36,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

 99%|█████████████████████████████████████████████████████████████████████████████▏| 1254/1267 [54:29<00:33,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 228886

 99%|█████████████████████████████████████████████████████████████████████████████▎| 1255/1267 [54:32<00:31,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 150590

 99%|█████████████████████████████████████████████████████████████████████████████▎| 1256/1267 [54:35<00:28,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

 99%|█████████████████████████████████████████████████████████████████████████████▍| 1257/1267 [54:37<00:25,  2.60s/it]

Created 300 windows of shape (128, 4) from sequence of length 111100

 99%|█████████████████████████████████████████████████████████████████████████████▍| 1258/1267 [54:40<00:23,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 21097

 99%|█████████████████████████████████████████████████████████████████████████████▌| 1259/1267 [54:42<00:20,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 19396

 99%|█████████████████████████████████████████████████████████████████████████████▌| 1260/1267 [54:45<00:17,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 4999

100%|█████████████████████████████████████████████████████████████████████████████▋| 1261/1267 [54:47<00:15,  2.56s/it]

Created 300 windows of shape (128, 4) from sequence of length 21200

100%|█████████████████████████████████████████████████████████████████████████████▋| 1262/1267 [54:50<00:12,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 75200

100%|█████████████████████████████████████████████████████████████████████████████▊| 1263/1267 [54:52<00:10,  2.55s/it]

Created 300 windows of shape (128, 4) from sequence of length 225461

100%|█████████████████████████████████████████████████████████████████████████████▊| 1264/1267 [54:55<00:07,  2.57s/it]

Created 300 windows of shape (128, 4) from sequence of length 147848

100%|█████████████████████████████████████████████████████████████████████████████▉| 1265/1267 [54:58<00:05,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 30593

100%|█████████████████████████████████████████████████████████████████████████████▉| 1266/1267 [55:00<00:02,  2.58s/it]

Created 300 windows of shape (128, 4) from sequence of length 102800

100%|██████████████████████████████████████████████████████████████████████████████| 1267/1267 [55:03<00:00,  2.61s/it]

Created 300 windows of shape (128, 4) from sequence of length 27997

(380100, 128, 4)

## 7.2 From continuous time-series to trainable windows

At this point, we have transformed the raw, per-file rocket test telemetry into a
single 3D NumPy array:

- Shape: `(380100, 128, 4)`
- Axes:
  - Axis 0: independent sliding windows (samples)
  - Axis 1: time steps within each window (`window_size = 128`)
  - Axis 2: features (`4` selected sensor channels)

Each sample now represents a short, fixed-length snippet of normalized sensor
behaviour. This is the format that sequence models (LSTMs, GANs on sequences,
VAEs, etc.) expect for training.

In this project, we will:
- train the **LSTM / GAN models** on these windows,
- optionally monitor performance on a held-out **validation** subset,
- later evaluate anomaly detection on separate test runs.

The next step in this notebook is to:
1. Split this large window set into **train** and **validation** subsets.
2. Persist the resulting arrays to `data/processed/` so that the modelling
   notebooks do not need to redo heavy preprocessing.

### 7.2.1 Simple train/validation split

We perform an 80/20 split of the windowed dataset into:
- `X_train`: used for training the Prophet-LSTM-GAN models
- `X_val`: used for monitoring validation loss and early stopping

Because the goal here is unsupervised modelling of *normal* behaviour, we only
split the input windows; labels will be defined later in the modelling /
evaluation notebook if needed.

In [20]:
# Train/validation split (80/20, no shuffle)

total_windows = X_train.shape[0]
val_fraction = 0.2
split_idx = int((1 - val_fraction) * total_windows)

X_train_final = X_train[:split_idx]   # 80%
X_val = X_train[split_idx:]           # 20%

print("Total windows:", total_windows)
print("Train windows:", X_train_final.shape, f"({X_train_final.shape[0]/total_windows:.1%})")
print("Val   windows:", X_val.shape, f"({X_val.shape[0]/total_windows:.1%})")

Total windows: 380100
Train windows: (304080, 128, 4) (80.0%)
Val   windows: (76020, 128, 4) (20.0%)

### 7.3 Saving processed arrays to `data/processed/`

To avoid re-running the expensive preprocessing and window generation every
time we open this notebook or a modelling notebook, we now persist the prepared
NumPy arrays to disk.

We save:

- `X_train_final.npy` : windowed training set
- `X_val.npy`         : windowed validation set

These files will be loaded directly by:

- `01_lstm_prophet_baseline.ipynb`
- `02_gan_anomaly_detection.ipynb`

so that those notebooks can focus purely on model architecture, training loops,
and evaluation, without touching raw CSVs.

In [21]:
# Save processed arrays to disk

PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

np.save(PROCESSED_DIR / "X_train_final.npy", X_train_final)
np.save(PROCESSED_DIR / "X_val.npy", X_val)

print("Saved:")
print(" -", PROCESSED_DIR / "X_train_final.npy")
print(" -", PROCESSED_DIR / "X_val.npy")

Saved:
 - C:\Users\aymisxx\Documents\GitHub\ProphetLSTM-GAN\data\processed\X_train_final.npy
 - C:\Users\aymisxx\Documents\GitHub\ProphetLSTM-GAN\data\processed\X_val.npy

### 8. Reload scaler and build sliding-window test set

In this step, we finish the preprocessing pipeline by constructing the test tensor `X_test`.

- We **reload the fitted StandardScaler** from disk, to ensure that the test set uses the **same normalization** as the training data.
- For each CSV in `data/raw/test`, we:
  - load the selected features (`P_cc`, `m_dot_ox`, `m_dot_f`, `T_cc`)
  - apply the saved scaler
  - build fixed-length sliding windows of length `WINDOW_SIZE` (e.g., 128 time steps) with stride `WINDOW_STRIDE`.
- We stream windows file-by-file into a Python list (instead of storing all full sequences at once) to reduce peak memory usage.
- Finally, we stack all windows into a single tensor `X_test` of shape `(num_windows_test, WINDOW_SIZE, num_features)` and save it as `X_test.npy` in `data/processed/`.

This completes **PHASE 2: Dataset + Preprocessing** for the project.

In [3]:
import numpy as np
import joblib
from pathlib import Path
from sklearn.preprocessing import StandardScaler

PROJECT_ROOT = Path(r"C:\Users\aymisxx\Documents\GitHub\ProphetLSTM-GAN")
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

# Load final train windows (already saved earlier)
X_train_path = PROCESSED_DIR / "X_train_final.npy"
X_train_final = np.load(X_train_path)

print("Loaded train windows:", X_train_final.shape)

# Flatten time dimension to refit scaler on all feature rows
flat = X_train_final.reshape(-1, X_train_final.shape[-1])

scaler = StandardScaler()
scaler.fit(flat)

print("Scaler refit on train windows.")

Loaded train windows: (304080, 128, 4)
Scaler refit on train windows.

In [4]:
scaler_save_path = PROCESSED_DIR / "scaler.pkl"
joblib.dump(scaler, scaler_save_path)
print("Scaler saved to:", scaler_save_path)

Scaler saved to: C:\Users\aymisxx\Documents\GitHub\ProphetLSTM-GAN\data\processed\scaler.pkl

In [5]:
import joblib

# Save the fitted scaler from earlier
scaler_save_path = PROCESSED_DIR / "scaler.pkl"
joblib.dump(scaler, scaler_save_path)

print("Scaler saved to:", scaler_save_path)

Scaler saved to: C:\Users\aymisxx\Documents\GitHub\ProphetLSTM-GAN\data\processed\scaler.pkl

In [8]:
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.preprocessing import StandardScaler
import joblib

# Paths
BASE_DIR = Path.cwd()
DATA_DIR = BASE_DIR / "data"
RAW_TRAIN_DIR = DATA_DIR / "raw" / "train"
RAW_TEST_DIR = DATA_DIR / "raw" / "test"
PROCESSED_DIR = DATA_DIR / "processed"
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

WINDOW_SIZE = 128
WINDOW_STEP = 16  # or 1 if you want denser windows

train_files = sorted(RAW_TRAIN_DIR.glob("*.csv"))
print("Total train CSVs found:", len(train_files))

# ---------- 1) Auto-discover common numeric feature columns ----------
def get_numeric_cols(path):
    df = pd.read_csv(path, nrows=5)
    numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
    # Drop obvious time columns
    drop_candidates = {c for c in numeric_cols if c.lower() in ("time", "t", "timestamp")}
    return [c for c in numeric_cols if c not in drop_candidates]

sample_files = train_files[:min(50, len(train_files))]
common_cols = None

for f in sample_files:
    try:
        cols = get_numeric_cols(f)
        if not cols:
            continue
        if common_cols is None:
            common_cols = set(cols)
        else:
            common_cols &= set(cols)
    except Exception as e:
        print(f"[WARN] Could not read {f.name} for column discovery: {e}")

if not common_cols:
    raise RuntimeError("Could not find any common numeric columns across the sample train CSVs.")

FEATURE_COLS = sorted(common_cols)
print(f"\n[INFO] Auto-detected {len(FEATURE_COLS)} common numeric feature columns:")
print(FEATURE_COLS)

# Save FEATURE_COLS for later (test set, training notebook)
np.save(PROCESSED_DIR / "FEATURE_COLS.npy", np.array(FEATURE_COLS, dtype=object))

# ---------- 2) Concatenate raw train data over all valid files ----------
train_rows = []
skipped_train = 0

for path in train_files:
    df = pd.read_csv(path)
    missing = [c for c in FEATURE_COLS if c not in df.columns]
    if missing:
        skipped_train += 1
        print(f"[WARN] Skipping TRAIN file {path.name} — missing {len(missing)} of FEATURE_COLS")
        continue
    arr = df[FEATURE_COLS].to_numpy(dtype=np.float32)
    train_rows.append(arr)

print(f"\nTrain files actually used: {len(train_rows)}, skipped: {skipped_train}")

if not train_rows:
    raise RuntimeError("No valid train files after applying FEATURE_COLS. Check CSV headers / folders.")

train_raw = np.concatenate(train_rows, axis=0)
print("Raw train concatenated shape:", train_raw.shape)

# ---------- 3) Fit scaler on train_raw and transform ----------
scaler = StandardScaler()
train_scaled = scaler.fit_transform(train_raw)
print("Train scaled shape:", train_scaled.shape)

# Save scaler
scaler_path = PROCESSED_DIR / "scaler.pkl"
joblib.dump(scaler, scaler_path)
print("Scaler saved to:", scaler_path)

# ---------- 4) Helper to build sliding windows from 2D array ----------
def build_windows_from_2d(data_2d, window_size, step):
    """
    data_2d: (N, F)
    returns: (num_windows, window_size, F)
    """
    n = len(data_2d)
    f = data_2d.shape[1]
    if n < window_size:
        return np.empty((0, window_size, f), dtype=np.float32)

    windows = []
    for start in range(0, n - window_size + 1, step):
        windows.append(data_2d[start:start + window_size])
    return np.stack(windows, axis=0)

# ---------- 5) Rebuild windows per file so we don't mix sequences ----------
X_train_windows = []

for path in train_files:
    df = pd.read_csv(path)
    if not set(FEATURE_COLS).issubset(df.columns):
        continue

    raw = df[FEATURE_COLS].to_numpy(dtype=np.float32)
    scaled = scaler.transform(raw)
    w = build_windows_from_2d(scaled, WINDOW_SIZE, WINDOW_STEP)
    if len(w):
        X_train_windows.append(w)

if not X_train_windows:
    raise RuntimeError("No train windows were built. Check window size/step vs file lengths.")

X_all = np.concatenate(X_train_windows, axis=0)
print("Total windowed train shape (before split):", X_all.shape)

# ---------- 6) Train/Val split along the first dimension ----------
val_fraction = 0.1
n_total = len(X_all)
n_val = int(n_total * val_fraction)

X_val = X_all[:n_val]
X_train = X_all[n_val:]

print("After split:")
print("  X_train:", X_train.shape)
print("  X_val:  ", X_val.shape)

# ---------- 7) Save arrays ----------
np.save(PROCESSED_DIR / "X_train.npy", X_train)
np.save(PROCESSED_DIR / "X_val.npy", X_val)

print("\nSaved to:")
print("  ", PROCESSED_DIR / "X_train.npy")
print("  ", PROCESSED_DIR / "X_val.npy")
print("\nTrain/val preprocessing complete.")

Total train CSVs found: 1267

[INFO] Auto-detected 5 common numeric feature columns:
['anomaly_code', 'mfr', 'thrust', 'ton', 'vl']

Train files actually used: 1267, skipped: 0
Raw train concatenated shape: (81180322, 5)
Train scaled shape: (81180322, 5)
Scaler saved to: C:\Users\aymisxx\Documents\GitHub\ProphetLSTM-GAN\data\processed\scaler.pkl
Total windowed train shape (before split): (5064525, 128, 5)
After split:
  X_train: (4558073, 128, 5)
  X_val:   (506452, 128, 5)

Saved to:
   C:\Users\aymisxx\Documents\GitHub\ProphetLSTM-GAN\data\processed\X_train.npy
   C:\Users\aymisxx\Documents\GitHub\ProphetLSTM-GAN\data\processed\X_val.npy

Train/val preprocessing complete.

In [9]:
import numpy as np
import pandas as pd
from pathlib import Path
import joblib

# Paths
BASE_DIR = Path.cwd()
DATA_DIR = BASE_DIR / "data"
RAW_TEST_DIR = DATA_DIR / "raw" / "test"
PROCESSED_DIR = DATA_DIR / "processed"

WINDOW_SIZE = 128
WINDOW_STEP = 16

# Reload scaler + feature list
scaler = joblib.load(PROCESSED_DIR / "scaler.pkl")
FEATURE_COLS = np.load(PROCESSED_DIR / "FEATURE_COLS.npy", allow_pickle=True).tolist()

print("Using FEATURE_COLS:", FEATURE_COLS)

test_files = sorted(RAW_TEST_DIR.glob("*.csv"))
print("Total test CSVs found:", len(test_files))

def build_windows_from_2d(data_2d, window_size, step):
    n = len(data_2d)
    f = data_2d.shape[1]
    if n < window_size:
        return np.empty((0, window_size, f), dtype=np.float32)

    windows = []
    for start in range(0, n - window_size + 1, step):
        windows.append(data_2d[start:start + window_size])
    return np.stack(windows, axis=0)

X_test_windows = []
skipped_test = 0

for path in test_files:
    df = pd.read_csv(path)
    if not set(FEATURE_COLS).issubset(df.columns):
        skipped_test += 1
        print(f"[WARN] Skipping TEST file {path.name} — missing some FEATURE_COLS")
        continue

    raw = df[FEATURE_COLS].to_numpy(dtype=np.float32)
    scaled = scaler.transform(raw)
    w = build_windows_from_2d(scaled, WINDOW_SIZE, WINDOW_STEP)
    if len(w):
        X_test_windows.append(w)

print(f"\nTest files used: {len(X_test_windows)}, skipped: {skipped_test}")

if not X_test_windows:
    raise RuntimeError("No test windows were built. Check FEATURE_COLS / headers.")

X_test = np.concatenate(X_test_windows, axis=0)
print("Final X_test shape:", X_test.shape)

np.save(PROCESSED_DIR / "X_test.npy", X_test)
print("Saved:", PROCESSED_DIR / "X_test.npy")

Using FEATURE_COLS: ['anomaly_code', 'mfr', 'thrust', 'ton', 'vl']
Total test CSVs found: 1344

ParserError: Error tokenizing data. C error: out of memory